import { FixityAlgorithm } from '@/files/domain/models/FixityAlgorithm'

export const mockFileUploadState = {
  'file1.jpg': {
    key: 'file1.jpg',
    progress: 100,
    storageId: 'storage1',
    uploading: false,
    fileSizeString: '2 MB',
    fileSize: 2000000,
    fileLastModified: 1700000000000,
    failed: false,
    done: true,
    removed: false,
    fileName: 'document.pdf',
    fileDir: undefined,
    fileType: 'application/pdf',
    checksumValue: 'abcd1234',
    checksumAlgorithm: FixityAlgorithm.MD5
  },
  file2: {
    key: 'file2',
    progress: 50,
    uploading: true,
    fileSizeString: '5 MB',
    fileSize: 5000000,
    fileLastModified: 1700000005000,
    failed: false,
    done: false,
    removed: false,
    fileName: 'image.png',
    fileDir: undefined,
    fileType: 'image/png',
    checksumAlgorithm: FixityAlgorithm.MD5
  },
  file3: {
    key: 'file3',
    progress: 10,
    uploading: true,
    fileSizeString: '8 MB',
    fileSize: 8000000,
    fileLastModified: 1700000010000,
    failed: false,
    done: false,
    removed: false,
    fileName: 'video.mp4',
    fileDir: undefined,
    fileType: 'video/mp4',
    checksumAlgorithm: FixityAlgorithm.MD5
  },
  file4: {
    key: 'file4',
    progress: 100,
    uploading: false,
    fileSizeString: '1.5 MB',
    fileSize: 1500000,
    fileLastModified: 1700000015000,
    failed: false,
    done: true,
    removed: false,
    fileName: 'spreadsheet.xlsx',
    fileDir: 'documents',
    fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    checksumAlgorithm: FixityAlgorithm.MD5
  },
  file5: {
    key: 'file5',
    progress: 0,
    uploading: false,
    fileSizeString: '3 MB',
    fileSize: 3000000,
    fileLastModified: 1700000020000,
    failed: true,
    done: false,
    removed: false,
    fileName: 'presentation.pptx',
    fileDir: 'slides',
    fileType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    checksumAlgorithm: FixityAlgorithm.MD5
  },
  file6: {
    key: 'file6',
    progress: 75,
    uploading: true,
    fileSizeString: '6 MB',
    fileSize: 6000000,
    fileLastModified: 1700000025000,
    failed: false,
    done: false,
    removed: false,
    fileName: 'audio_super_long_name_file.mp3',
    fileDir: '',
    fileType: 'audio/mpeg',
    checksumAlgorithm: FixityAlgorithm.MD5
  },
  file7: {
    key: 'file7',
    progress: 100,
    uploading: false,
    fileSizeString: '700 KB',
    fileSize: 700000,
    fileLastModified: 1700000030000,
    failed: false,
    done: true,
    removed: false,
    fileName: 'notes.txt',
    fileDir: 'documents',
    fileType: 'text/plain',
    checksumAlgorithm: FixityAlgorithm.MD5
  },
  file8: {
    key: 'file8',
    progress: 20,
    uploading: true,
    fileSizeString: '15 MB',
    fileSize: 15000000,
    fileLastModified: 1700000035000,
    failed: false,
    done: false,
    removed: false,
    fileName: 'compressed.zip',
    fileDir: 'archives',
    fileType: 'application/zip',
    checksumAlgorithm: FixityAlgorithm.MD5
  },
  file9: {
    key: 'file9',
    progress: 100,
    uploading: false,
    fileSizeString: '10 MB',
    fileSize: 10000000,
    fileLastModified: 1700000040000,
    failed: false,
    done: true,
    removed: false,
    fileName: 'report.docx',
    fileDir: 'reports',
    fileType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    checksumAlgorithm: FixityAlgorithm.MD5
  },
  file10: {
    key: 'file10',
    progress: 0,
    uploading: false,
    fileSizeString: '12 MB',
    fileSize: 12000000,
    fileLastModified: 1700000045000,
    failed: true,
    done: false,
    removed: false,
    fileName: 'corrupted-file.dat',
    fileDir: 'unknown',
    fileType: 'application/octet-stream',
    checksumAlgorithm: FixityAlgorithm.MD5
  }
}
