import { MetadataBlockInfo } from '../../../../../src/metadata-block-info/domain/models/MetadataBlockInfo'

export class AstrophysicsMetadataBlockInfoMother {
  static get(): MetadataBlockInfo {
    return {
      id: 4,
      name: 'astrophysics',
      displayName: 'Astronomy and Astrophysics Metadata',
      displayOnCreate: false,
      metadataFields: {
        astroType: {
          name: 'astroType',
          displayName: 'Type',
          title: 'Type',
          type: 'TEXT',
          watermark: '',
          description: 'The nature or genre of the content of the files in the dataset.',
          multiple: true,
          isControlledVocabulary: true,
          controlledVocabularyValues: [
            'Image',
            'Mosaic',
            'EventList',
            'Spectrum',
            'Cube',
            'Table',
            'Catalog',
            'LightCurve',
            'Simulation',
            'Figure',
            'Artwork',
            'Animation',
            'PrettyPicture',
            'Documentation',
            'Other',
            'Library',
            'Press Release',
            'Facsimile',
            'Historical',
            'Observation',
            'Object',
            'Value',
            'ValuePair',
            'Survey'
          ],
          displayFormat: '',
          isRequired: false,
          displayOrder: 0,
          typeClass: 'controlledVocabulary',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        astroFacility: {
          name: 'astroFacility',
          displayName: 'Facility',
          title: 'Facility',
          type: 'TEXT',
          watermark: '',
          description: 'The observatory or facility where the data was obtained. ',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 1,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        astroInstrument: {
          name: 'astroInstrument',
          displayName: 'Instrument',
          title: 'Instrument',
          type: 'TEXT',
          watermark: '',
          description: 'The instrument used to collect the data.',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 2,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        astroObject: {
          name: 'astroObject',
          displayName: 'Object',
          title: 'Object',
          type: 'TEXT',
          watermark: '',
          description:
            'Astronomical Objects represented in the data (Given as SIMBAD recognizable names preferred).',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 3,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'resolution.Spatial': {
          name: 'resolution.Spatial',
          displayName: 'Spatial Resolution',
          title: 'Spatial Resolution',
          type: 'TEXT',
          watermark: '',
          description:
            'The spatial (angular) resolution that is typical of the observations, in decimal degrees.',
          multiple: false,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 4,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'resolution.Spectral': {
          name: 'resolution.Spectral',
          displayName: 'Spectral Resolution',
          title: 'Spectral Resolution',
          type: 'TEXT',
          watermark: '',
          description:
            'The spectral resolution that is typical of the observations, given as the ratio \\u03bb/\\u0394\\u03bb.',
          multiple: false,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 5,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'resolution.Temporal': {
          name: 'resolution.Temporal',
          displayName: 'Time Resolution',
          title: 'Time Resolution',
          type: 'TEXT',
          watermark: '',
          description:
            'The temporal resolution that is typical of the observations, given in seconds.',
          multiple: false,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 6,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'coverage.Spectral.Bandpass': {
          name: 'coverage.Spectral.Bandpass',
          displayName: 'Bandpass',
          title: 'Bandpass',
          type: 'TEXT',
          watermark: '',
          description: 'Conventional bandpass name',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 7,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'coverage.Spectral.CentralWavelength': {
          name: 'coverage.Spectral.CentralWavelength',
          displayName: 'Central Wavelength (m)',
          title: 'Central Wavelength (m)',
          type: 'FLOAT',
          watermark: 'Enter a floating-point number.',
          description: 'The central wavelength of the spectral bandpass, in meters.',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 8,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'coverage.Spectral.Wavelength': {
          name: 'coverage.Spectral.Wavelength',
          displayName: 'Wavelength Range',
          title: 'Wavelength Range',
          type: 'NONE',
          watermark: 'Enter a floating-point number.',
          description: 'The minimum and maximum wavelength of the spectral bandpass.',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 9,
          typeClass: 'compound',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false,
          childMetadataFields: {
            'coverage.Spectral.MinimumWavelength': {
              name: 'coverage.Spectral.MinimumWavelength',
              displayName: 'Wavelength Range Minimum (m)',
              title: 'Minimum (m)',
              type: 'FLOAT',
              watermark: 'Enter a floating-point number.',
              description: 'The minimum wavelength of the spectral bandpass, in meters.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '',
              isRequired: false,
              displayOrder: 10,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            },
            'coverage.Spectral.MaximumWavelength': {
              name: 'coverage.Spectral.MaximumWavelength',
              displayName: 'Wavelength Range Maximum (m)',
              title: 'Maximum (m)',
              type: 'FLOAT',
              watermark: 'Enter a floating-point number.',
              description: 'The maximum wavelength of the spectral bandpass, in meters.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '',
              isRequired: false,
              displayOrder: 11,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            }
          }
        },
        'coverage.Temporal': {
          name: 'coverage.Temporal',
          displayName: 'Dataset Date Range',
          title: 'Dataset Date Range',
          type: 'NONE',
          watermark: '',
          description: ' Time period covered by the data.',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 12,
          typeClass: 'compound',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false,
          childMetadataFields: {
            'coverage.Temporal.StartTime': {
              name: 'coverage.Temporal.StartTime',
              displayName: 'Dataset Date Range Start',
              title: 'Start',
              type: 'DATE',
              watermark: 'YYYY-MM-DD',
              description: 'Dataset Start Date',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '',
              isRequired: false,
              displayOrder: 13,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            },
            'coverage.Temporal.StopTime': {
              name: 'coverage.Temporal.StopTime',
              displayName: 'Dataset Date Range End',
              title: 'End',
              type: 'DATE',
              watermark: 'YYYY-MM-DD',
              description: 'Dataset End Date',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '',
              isRequired: false,
              displayOrder: 14,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            }
          }
        },
        'coverage.Spatial': {
          name: 'coverage.Spatial',
          displayName: 'Sky Coverage',
          title: 'Sky Coverage',
          type: 'TEXT',
          watermark: '',
          description: 'The sky coverage of the data object.',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 15,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'coverage.Depth': {
          name: 'coverage.Depth',
          displayName: 'Depth Coverage',
          title: 'Depth Coverage',
          type: 'FLOAT',
          watermark: 'Enter a floating-point number.',
          description: 'The (typical) depth coverage, or sensitivity, of the data object in Jy.',
          multiple: false,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 16,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'coverage.ObjectDensity': {
          name: 'coverage.ObjectDensity',
          displayName: 'Object Density',
          title: 'Object Density',
          type: 'FLOAT',
          watermark: 'Enter a floating-point number.',
          description:
            'The (typical) density of objects, catalog entries, telescope pointings, etc., on the sky, in number per square degree.',
          multiple: false,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 17,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'coverage.ObjectCount': {
          name: 'coverage.ObjectCount',
          displayName: 'Object Count',
          title: 'Object Count',
          type: 'INT',
          watermark: 'Enter an integer.',
          description: 'The total number of objects, catalog entries, etc., in the data object.',
          multiple: false,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 18,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'coverage.SkyFraction': {
          name: 'coverage.SkyFraction',
          displayName: 'Fraction of Sky',
          title: 'Fraction of Sky',
          type: 'FLOAT',
          watermark: 'Enter a floating-point number.',
          description:
            'The fraction of the sky represented in the observations, ranging from 0 to 1.',
          multiple: false,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 19,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'coverage.Polarization': {
          name: 'coverage.Polarization',
          displayName: 'Polarization',
          title: 'Polarization',
          type: 'TEXT',
          watermark: '',
          description: 'The polarization coverage',
          multiple: false,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 20,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        redshiftType: {
          name: 'redshiftType',
          displayName: 'RedshiftType',
          title: 'RedshiftType',
          type: 'TEXT',
          watermark: '',
          description:
            'RedshiftType string C "Redshift"; or "Optical" or "Radio" definitions of Doppler velocity used in the data object.',
          multiple: false,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 21,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'resolution.Redshift': {
          name: 'resolution.Redshift',
          displayName: 'Redshift Resolution',
          title: 'Redshift Resolution',
          type: 'FLOAT',
          watermark: 'Enter a floating-point number.',
          description:
            'The resolution in redshift (unitless) or Doppler velocity (km/s) in the data object.',
          multiple: false,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 22,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        'coverage.RedshiftValue': {
          name: 'coverage.RedshiftValue',
          displayName: 'Redshift Value',
          title: 'Redshift Value',
          type: 'FLOAT',
          watermark: 'Enter a floating-point number.',
          description:
            'The value of the redshift (unitless) or Doppler velocity (km/s in the data object.',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 23,
          typeClass: 'compound',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false,
          childMetadataFields: {
            'coverage.Redshift.MinimumValue': {
              name: 'coverage.Redshift.MinimumValue',
              displayName: 'Redshift Value Minimum',
              title: 'Minimum',
              type: 'FLOAT',
              watermark: 'Enter a floating-point number.',
              description:
                'The minimum value of the redshift (unitless) or Doppler velocity (km/s in the data object.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '',
              isRequired: false,
              displayOrder: 24,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            },
            'coverage.Redshift.MaximumValue': {
              name: 'coverage.Redshift.MaximumValue',
              displayName: 'Redshift Value Maximum',
              title: 'Maximum',
              type: 'FLOAT',
              watermark: 'Enter a floating-point number.',
              description:
                'The maximum value of the redshift (unitless) or Doppler velocity (km/s in the data object.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '',
              isRequired: false,
              displayOrder: 25,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            }
          }
        }
      }
    }
  }
}
