import { MetadataField } from '../../../../../src/metadata-block-info/domain/models/MetadataBlockInfo'

export class FacetableMetadataFieldMother {
  static getAll(): MetadataField[] {
    return [
      {
        name: 'authorName',
        displayName: 'Author Name',
        title: 'Name',
        type: 'TEXT',
        watermark: '1) Family Name, Given Name or 2) Organization XYZ',
        description:
          "The name of the author, such as the person's name or the name of an organization",
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE',
        isRequired: true,
        displayOrder: 8,
        typeClass: 'primitive',
        displayOnCreate: true
      },
      {
        name: 'authorAffiliation',
        displayName: 'Author Affiliation',
        title: 'Affiliation',
        type: 'TEXT',
        watermark: 'Organization XYZ',
        description:
          "The name of the entity affiliated with the author, e.g. an organization's name",
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '(#VALUE)',
        isRequired: false,
        displayOrder: 9,
        typeClass: 'primitive',
        displayOnCreate: true
      },
      {
        name: 'subject',
        displayName: 'Subject',
        title: 'Subject',
        type: 'TEXT',
        watermark: '',
        description: 'The area of study relevant to the Dataset',
        multiple: true,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'Agricultural Sciences',
          'Arts and Humanities',
          'Astronomy and Astrophysics',
          'Business and Management',
          'Chemistry',
          'Computer and Information Science',
          'Earth and Environmental Sciences',
          'Engineering',
          'Law',
          'Mathematical Sciences',
          'Medicine, Health and Life Sciences',
          'Physics',
          'Social Sciences',
          'Other'
        ],
        displayFormat: '',
        isRequired: true,
        displayOrder: 19,
        typeClass: 'controlledVocabulary',
        displayOnCreate: true
      },
      {
        name: 'keywordValue',
        displayName: 'Keyword Term',
        title: 'Term',
        type: 'TEXT',
        watermark: '',
        description: 'A key term that describes important aspects of the Dataset',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE',
        isRequired: false,
        displayOrder: 21,
        typeClass: 'primitive',
        displayOnCreate: true
      },
      {
        name: 'topicClassValue',
        displayName: 'Topic Classification Term',
        title: 'Term',
        type: 'TEXT',
        watermark: '',
        description: 'A topic or subject term',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE',
        isRequired: false,
        displayOrder: 26,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'language',
        displayName: 'Language',
        title: 'Language',
        type: 'TEXT',
        watermark: '',
        description: "A language that the Dataset's files is written in",
        multiple: true,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'Abkhaz',
          'Afar',
          'Afrikaans',
          'Akan',
          'Albanian',
          'Amharic',
          'Arabic',
          'Aragonese',
          'Armenian',
          'Assamese',
          'Avaric',
          'Avestan',
          'Aymara',
          'Azerbaijani',
          'Bambara',
          'Bashkir',
          'Basque',
          'Belarusian',
          'Bengali, Bangla',
          'Bihari',
          'Bislama',
          'Bosnian',
          'Breton',
          'Bulgarian',
          'Burmese',
          'Catalan,Valencian',
          'Chamorro',
          'Chechen',
          'Chichewa, Chewa, Nyanja',
          'Chinese',
          'Chuvash',
          'Cornish',
          'Corsican',
          'Cree',
          'Croatian',
          'Czech',
          'Danish',
          'Divehi, Dhivehi, Maldivian',
          'Dutch',
          'Dzongkha',
          'English',
          'Esperanto',
          'Estonian',
          'Ewe',
          'Faroese',
          'Fijian',
          'Finnish',
          'French',
          'Fula, Fulah, Pulaar, Pular',
          'Galician',
          'Georgian',
          'German',
          'Greek (modern)',
          'Guaraní',
          'Gujarati',
          'Haitian, Haitian Creole',
          'Hausa',
          'Hebrew (modern)',
          'Herero',
          'Hindi',
          'Hiri Motu',
          'Hungarian',
          'Interlingua',
          'Indonesian',
          'Interlingue',
          'Irish',
          'Igbo',
          'Inupiaq',
          'Ido',
          'Icelandic',
          'Italian',
          'Inuktitut',
          'Japanese',
          'Javanese',
          'Kalaallisut, Greenlandic',
          'Kannada',
          'Kanuri',
          'Kashmiri',
          'Kazakh',
          'Khmer',
          'Kikuyu, Gikuyu',
          'Kinyarwanda',
          'Kyrgyz',
          'Komi',
          'Kongo',
          'Korean',
          'Kurdish',
          'Kwanyama, Kuanyama',
          'Latin',
          'Luxembourgish, Letzeburgesch',
          'Ganda',
          'Limburgish, Limburgan, Limburger',
          'Lingala',
          'Lao',
          'Lithuanian',
          'Luba-Katanga',
          'Latvian',
          'Manx',
          'Macedonian',
          'Malagasy',
          'Malay',
          'Malayalam',
          'Maltese',
          'Māori',
          'Marathi (Marāṭhī)',
          'Marshallese',
          'Mixtepec Mixtec',
          'Mongolian',
          'Nauru',
          'Navajo, Navaho',
          'Northern Ndebele',
          'Nepali',
          'Ndonga',
          'Norwegian Bokmål',
          'Norwegian Nynorsk',
          'Norwegian',
          'Nuosu',
          'Southern Ndebele',
          'Occitan',
          'Ojibwe, Ojibwa',
          'Old Church Slavonic,Church Slavonic,Old Bulgarian',
          'Oromo',
          'Oriya',
          'Ossetian, Ossetic',
          'Panjabi, Punjabi',
          'Pāli',
          'Persian (Farsi)',
          'Polish',
          'Pashto, Pushto',
          'Portuguese',
          'Quechua',
          'Romansh',
          'Kirundi',
          'Romanian',
          'Russian',
          'Sanskrit (Saṁskṛta)',
          'Sardinian',
          'Sindhi',
          'Northern Sami',
          'Samoan',
          'Sango',
          'Serbian',
          'Scottish Gaelic, Gaelic',
          'Shona',
          'Sinhala, Sinhalese',
          'Slovak',
          'Slovene',
          'Somali',
          'Southern Sotho',
          'Spanish, Castilian',
          'Sundanese',
          'Swahili',
          'Swati',
          'Swedish',
          'Tamil',
          'Telugu',
          'Tajik',
          'Thai',
          'Tigrinya',
          'Tibetan Standard, Tibetan, Central',
          'Turkmen',
          'Tagalog',
          'Tswana',
          'Tonga (Tonga Islands)',
          'Turkish',
          'Tsonga',
          'Tatar',
          'Twi',
          'Tahitian',
          'Uyghur, Uighur',
          'Ukrainian',
          'Urdu',
          'Uzbek',
          'Venda',
          'Vietnamese',
          'Volapük',
          'Walloon',
          'Welsh',
          'Wolof',
          'Western Frisian',
          'Xhosa',
          'Yiddish',
          'Yoruba',
          'Zhuang, Chuang',
          'Zulu',
          'Not applicable'
        ],
        displayFormat: '',
        isRequired: false,
        displayOrder: 35,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      },
      {
        name: 'producerName',
        displayName: 'Producer Name',
        title: 'Name',
        type: 'TEXT',
        watermark: '1) FamilyName, GivenName or 2) Organization',
        description:
          "The name of the entity, e.g. the person's name or the name of an organization",
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE',
        isRequired: true,
        displayOrder: 37,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'productionDate',
        displayName: 'Production Date',
        title: 'Production Date',
        type: 'DATE',
        watermark: 'YYYY-MM-DD',
        description:
          'The date when the data were produced (not distributed, published, or archived)',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 42,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'productionPlace',
        displayName: 'Production Location',
        title: 'Production Location',
        type: 'TEXT',
        watermark: '',
        description:
          'The location where the data and any related materials were produced or collected',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 43,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'contributorType',
        displayName: 'Contributor Type',
        title: 'Type',
        type: 'TEXT',
        watermark: '',
        description: 'Indicates the type of contribution made to the dataset',
        multiple: false,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'Data Collector',
          'Data Curator',
          'Data Manager',
          'Editor',
          'Funder',
          'Hosting Institution',
          'Project Leader',
          'Project Manager',
          'Project Member',
          'Related Person',
          'Researcher',
          'Research Group',
          'Rights Holder',
          'Sponsor',
          'Supervisor',
          'Work Package Leader',
          'Other'
        ],
        displayFormat: '#VALUE ',
        isRequired: false,
        displayOrder: 45,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      },
      {
        name: 'contributorName',
        displayName: 'Contributor Name',
        title: 'Name',
        type: 'TEXT',
        watermark: '1) FamilyName, GivenName or 2) Organization',
        description:
          "The name of the contributor, e.g. the person's name or the name of an organization",
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE',
        isRequired: false,
        displayOrder: 46,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'grantNumberAgency',
        displayName: 'Funding Information Agency',
        title: 'Agency',
        type: 'TEXT',
        watermark: 'Organization XYZ',
        description: 'The agency that provided financial support for the Dataset',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE',
        isRequired: false,
        displayOrder: 48,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'grantNumberValue',
        displayName: 'Funding Information Identifier',
        title: 'Identifier',
        type: 'TEXT',
        watermark: '',
        description:
          'The grant identifier or contract identifier of the agency that provided financial support for the Dataset',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE',
        isRequired: false,
        displayOrder: 49,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'distributorName',
        displayName: 'Distributor Name',
        title: 'Name',
        type: 'TEXT',
        watermark: '1) FamilyName, GivenName or 2) Organization',
        description:
          "The name of the entity, e.g. the person's name or the name of an organization",
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE',
        isRequired: false,
        displayOrder: 51,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'distributionDate',
        displayName: 'Distribution Date',
        title: 'Distribution Date',
        type: 'DATE',
        watermark: 'YYYY-MM-DD',
        description: 'The date when the Dataset was made available for distribution/presentation',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 56,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'dateOfDeposit',
        displayName: 'Deposit Date',
        title: 'Deposit Date',
        type: 'DATE',
        watermark: 'YYYY-MM-DD',
        description: 'The date when the Dataset was deposited into the repository',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 58,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'timePeriodCoveredStart',
        displayName: 'Time Period Start Date',
        title: 'Start Date',
        type: 'DATE',
        watermark: 'YYYY-MM-DD',
        description: 'The start date of the time period that the data refer to',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#NAME: #VALUE ',
        isRequired: false,
        displayOrder: 60,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'timePeriodCoveredEnd',
        displayName: 'Time Period End Date',
        title: 'End Date',
        type: 'DATE',
        watermark: 'YYYY-MM-DD',
        description: 'The end date of the time period that the data refer to',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#NAME: #VALUE ',
        isRequired: false,
        displayOrder: 61,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'kindOfData',
        displayName: 'Data Type',
        title: 'Data Type',
        type: 'TEXT',
        watermark: '',
        description:
          'The type of data included in the files (e.g. survey data, clinical data, or machine-readable text)',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 65,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'seriesName',
        displayName: 'Series Name',
        title: 'Name',
        type: 'TEXT',
        watermark: '',
        description: 'The name of the dataset series',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE',
        isRequired: false,
        displayOrder: 67,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'country',
        displayName: 'Geographic Coverage Country / Nation',
        title: 'Country / Nation',
        type: 'TEXT',
        watermark: '',
        description: 'The country or nation that the Dataset is about.',
        multiple: false,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'Afghanistan',
          'Albania',
          'Algeria',
          'American Samoa',
          'Andorra',
          'Angola',
          'Anguilla',
          'Antarctica',
          'Antigua and Barbuda',
          'Argentina',
          'Armenia',
          'Aruba',
          'Australia',
          'Austria',
          'Azerbaijan',
          'Bahamas',
          'Bahrain',
          'Bangladesh',
          'Barbados',
          'Belarus',
          'Belgium',
          'Belize',
          'Benin',
          'Bermuda',
          'Bhutan',
          'Bolivia, Plurinational State of',
          'Bonaire, Sint Eustatius and Saba',
          'Bosnia and Herzegovina',
          'Botswana',
          'Bouvet Island',
          'Brazil',
          'British Indian Ocean Territory',
          'Brunei Darussalam',
          'Bulgaria',
          'Burkina Faso',
          'Burundi',
          'Cambodia',
          'Cameroon',
          'Canada',
          'Cape Verde',
          'Cayman Islands',
          'Central African Republic',
          'Chad',
          'Chile',
          'China',
          'Christmas Island',
          'Cocos (Keeling) Islands',
          'Colombia',
          'Comoros',
          'Congo',
          'Congo, the Democratic Republic of the',
          'Cook Islands',
          'Costa Rica',
          'Croatia',
          'Cuba',
          'Curaçao',
          'Cyprus',
          'Czech Republic',
          "Côte d'Ivoire",
          'Denmark',
          'Djibouti',
          'Dominica',
          'Dominican Republic',
          'Ecuador',
          'Egypt',
          'El Salvador',
          'Equatorial Guinea',
          'Eritrea',
          'Estonia',
          'Ethiopia',
          'Falkland Islands (Malvinas)',
          'Faroe Islands',
          'Fiji',
          'Finland',
          'France',
          'French Guiana',
          'French Polynesia',
          'French Southern Territories',
          'Gabon',
          'Gambia',
          'Georgia',
          'Germany',
          'Ghana',
          'Gibraltar',
          'Greece',
          'Greenland',
          'Grenada',
          'Guadeloupe',
          'Guam',
          'Guatemala',
          'Guernsey',
          'Guinea',
          'Guinea-Bissau',
          'Guyana',
          'Haiti',
          'Heard Island and Mcdonald Islands',
          'Holy See (Vatican City State)',
          'Honduras',
          'Hong Kong',
          'Hungary',
          'Iceland',
          'India',
          'Indonesia',
          'Iran, Islamic Republic of',
          'Iraq',
          'Ireland',
          'Isle of Man',
          'Israel',
          'Italy',
          'Jamaica',
          'Japan',
          'Jersey',
          'Jordan',
          'Kazakhstan',
          'Kenya',
          'Kiribati',
          "Korea, Democratic People's Republic of",
          'Korea, Republic of',
          'Kuwait',
          'Kyrgyzstan',
          "Lao People's Democratic Republic",
          'Latvia',
          'Lebanon',
          'Lesotho',
          'Liberia',
          'Libya',
          'Liechtenstein',
          'Lithuania',
          'Luxembourg',
          'Macao',
          'Macedonia, the Former Yugoslav Republic of',
          'Madagascar',
          'Malawi',
          'Malaysia',
          'Maldives',
          'Mali',
          'Malta',
          'Marshall Islands',
          'Martinique',
          'Mauritania',
          'Mauritius',
          'Mayotte',
          'Mexico',
          'Micronesia, Federated States of',
          'Moldova, Republic of',
          'Monaco',
          'Mongolia',
          'Montenegro',
          'Montserrat',
          'Morocco',
          'Mozambique',
          'Myanmar',
          'Namibia',
          'Nauru',
          'Nepal',
          'Netherlands',
          'New Caledonia',
          'New Zealand',
          'Nicaragua',
          'Niger',
          'Nigeria',
          'Niue',
          'Norfolk Island',
          'Northern Mariana Islands',
          'Norway',
          'Oman',
          'Pakistan',
          'Palau',
          'Palestine, State of',
          'Panama',
          'Papua New Guinea',
          'Paraguay',
          'Peru',
          'Philippines',
          'Pitcairn',
          'Poland',
          'Portugal',
          'Puerto Rico',
          'Qatar',
          'Romania',
          'Russian Federation',
          'Rwanda',
          'Réunion',
          'Saint Barthélemy',
          'Saint Helena, Ascension and Tristan da Cunha',
          'Saint Kitts and Nevis',
          'Saint Lucia',
          'Saint Martin (French part)',
          'Saint Pierre and Miquelon',
          'Saint Vincent and the Grenadines',
          'Samoa',
          'San Marino',
          'Sao Tome and Principe',
          'Saudi Arabia',
          'Senegal',
          'Serbia',
          'Seychelles',
          'Sierra Leone',
          'Singapore',
          'Sint Maarten (Dutch part)',
          'Slovakia',
          'Slovenia',
          'Solomon Islands',
          'Somalia',
          'South Africa',
          'South Georgia and the South Sandwich Islands',
          'South Sudan',
          'Spain',
          'Sri Lanka',
          'Sudan',
          'Suriname',
          'Svalbard and Jan Mayen',
          'Swaziland',
          'Sweden',
          'Switzerland',
          'Syrian Arab Republic',
          'Taiwan, Province of China',
          'Tajikistan',
          'Tanzania, United Republic of',
          'Thailand',
          'Timor-Leste',
          'Togo',
          'Tokelau',
          'Tonga',
          'Trinidad and Tobago',
          'Tunisia',
          'Turkey',
          'Turkmenistan',
          'Turks and Caicos Islands',
          'Tuvalu',
          'Uganda',
          'Ukraine',
          'United Arab Emirates',
          'United Kingdom',
          'United States',
          'United States Minor Outlying Islands',
          'Uruguay',
          'Uzbekistan',
          'Vanuatu',
          'Venezuela, Bolivarian Republic of',
          'Viet Nam',
          'Virgin Islands, British',
          'Virgin Islands, U.S.',
          'Wallis and Futuna',
          'Western Sahara',
          'Yemen',
          'Zambia',
          'Zimbabwe',
          'Åland Islands'
        ],
        displayFormat: '#VALUE, ',
        isRequired: false,
        displayOrder: 1,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      },
      {
        name: 'state',
        displayName: 'Geographic Coverage State / Province',
        title: 'State / Province',
        type: 'TEXT',
        watermark: '',
        description:
          'The state or province that the Dataset is about. Use GeoNames for correct spelling and avoid abbreviations.',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE, ',
        isRequired: false,
        displayOrder: 2,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'city',
        displayName: 'Geographic Coverage City',
        title: 'City',
        type: 'TEXT',
        watermark: '',
        description:
          'The name of the city that the Dataset is about. Use GeoNames for correct spelling and avoid abbreviations.',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE, ',
        isRequired: false,
        displayOrder: 3,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'otherGeographicCoverage',
        displayName: 'Geographic Coverage Other',
        title: 'Other',
        type: 'TEXT',
        watermark: '',
        description: 'Other information on the geographic coverage of the data.',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '#VALUE, ',
        isRequired: false,
        displayOrder: 4,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'geographicUnit',
        displayName: 'Geographic Unit',
        title: 'Geographic Unit',
        type: 'TEXT',
        watermark: '',
        description:
          'Lowest level of geographic aggregation covered by the Dataset, e.g., village, county, region.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 5,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'unitOfAnalysis',
        displayName: 'Unit of Analysis',
        title: 'Unit of Analysis',
        type: 'TEXTBOX',
        watermark: '',
        description:
          "Basic unit of analysis or observation that this Dataset describes, such as individuals, families/households, groups, institutions/organizations, administrative units, and more. For information about the DDI's controlled vocabulary for this element, please refer to the DDI web page at http://www.ddialliance.org/controlled-vocabularies.",
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 0,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'universe',
        displayName: 'Universe',
        title: 'Universe',
        type: 'TEXTBOX',
        watermark: '',
        description:
          'Description of the population covered by the data in the file; the group of people or other elements that are the object of the study and to which the study results refer. Age, nationality, and residence commonly help to  delineate a given universe, but any number of other factors may be used, such as age limits, sex, marital status, race, ethnic group, nationality, income, veteran status, criminal convictions, and more. The universe may consist of elements other than persons, such as housing units, court cases, deaths, countries, and so on. In general, it should be possible to tell from the description of the universe whether a given individual or element is a member of the population under study. Also known as the universe of interest, population of interest, and target population.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 1,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'timeMethod',
        displayName: 'Time Method',
        title: 'Time Method',
        type: 'TEXT',
        watermark: '',
        description:
          'The time method or time dimension of the data collection, such as panel, cross-sectional, trend, time- series, or other.',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 2,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'frequencyOfDataCollection',
        displayName: 'Frequency',
        title: 'Frequency',
        type: 'TEXT',
        watermark: '',
        description:
          'If the data collected includes more than one point in time, indicate the frequency with which the data was collected; that is, monthly, quarterly, or other.',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 5,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'responseRate',
        displayName: 'Response Rate',
        title: 'Response Rate',
        type: 'TEXTBOX',
        watermark: '',
        description: 'Percentage of sample members who provided information.',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 19,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'astroType',
        displayName: 'Type',
        title: 'Type',
        type: 'TEXT',
        watermark: '',
        description: 'The nature or genre of the content of the files in the dataset.',
        multiple: true,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'Image',
          'Mosaic',
          'EventList',
          'Spectrum',
          'Cube',
          'Table',
          'Catalog',
          'LightCurve',
          'Simulation',
          'Figure',
          'Artwork',
          'Animation',
          'PrettyPicture',
          'Documentation',
          'Other',
          'Library',
          'Press Release',
          'Facsimile',
          'Historical',
          'Observation',
          'Object',
          'Value',
          'ValuePair',
          'Survey'
        ],
        displayFormat: '',
        isRequired: false,
        displayOrder: 0,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      },
      {
        name: 'astroFacility',
        displayName: 'Facility',
        title: 'Facility',
        type: 'TEXT',
        watermark: '',
        description: 'The observatory or facility where the data was obtained. ',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 1,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'astroInstrument',
        displayName: 'Instrument',
        title: 'Instrument',
        type: 'TEXT',
        watermark: '',
        description: 'The instrument used to collect the data.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 2,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'astroObject',
        displayName: 'Object',
        title: 'Object',
        type: 'TEXT',
        watermark: '',
        description:
          'Astronomical Objects represented in the data (Given as SIMBAD recognizable names preferred).',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 3,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'resolution.Spatial',
        displayName: 'Spatial Resolution',
        title: 'Spatial Resolution',
        type: 'TEXT',
        watermark: '',
        description:
          'The spatial (angular) resolution that is typical of the observations, in decimal degrees.',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 4,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'resolution.Spectral',
        displayName: 'Spectral Resolution',
        title: 'Spectral Resolution',
        type: 'TEXT',
        watermark: '',
        description:
          'The spectral resolution that is typical of the observations, given as the ratio \\u03bb/\\u0394\\u03bb.',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 5,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'coverage.Spectral.Bandpass',
        displayName: 'Bandpass',
        title: 'Bandpass',
        type: 'TEXT',
        watermark: '',
        description: 'Conventional bandpass name',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 7,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'coverage.Spectral.CentralWavelength',
        displayName: 'Central Wavelength (m)',
        title: 'Central Wavelength (m)',
        type: 'FLOAT',
        watermark: 'Enter a floating-point number.',
        description: 'The central wavelength of the spectral bandpass, in meters.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 8,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'coverage.Spectral.MinimumWavelength',
        displayName: 'Wavelength Range Minimum (m)',
        title: 'Minimum (m)',
        type: 'FLOAT',
        watermark: 'Enter a floating-point number.',
        description: 'The minimum wavelength of the spectral bandpass, in meters.',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 10,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'coverage.Spectral.MaximumWavelength',
        displayName: 'Wavelength Range Maximum (m)',
        title: 'Maximum (m)',
        type: 'FLOAT',
        watermark: 'Enter a floating-point number.',
        description: 'The maximum wavelength of the spectral bandpass, in meters.',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 11,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'coverage.Temporal.StartTime',
        displayName: 'Dataset Date Range Start',
        title: 'Start',
        type: 'DATE',
        watermark: 'YYYY-MM-DD',
        description: 'Dataset Start Date',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 13,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'coverage.Temporal.StopTime',
        displayName: 'Dataset Date Range End',
        title: 'End',
        type: 'DATE',
        watermark: 'YYYY-MM-DD',
        description: 'Dataset End Date',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 14,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'studyDesignType',
        displayName: 'Design Type',
        title: 'Design Type',
        type: 'TEXT',
        watermark: '',
        description: 'Design types that are based on the overall experimental design.',
        multiple: true,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'Case Control',
          'Cross Sectional',
          'Cohort Study',
          'Nested Case Control Design',
          'Not Specified',
          'Parallel Group Design',
          'Perturbation Design',
          'Randomized Controlled Trial',
          'Technological Design',
          'Other'
        ],
        displayFormat: '',
        isRequired: false,
        displayOrder: 0,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      },
      {
        name: 'studyOtherDesignType',
        displayName: 'Other Design Type',
        title: 'Other Design Type',
        type: 'TEXT',
        watermark: '',
        description:
          'If Other was selected in Design Type, list any other design types that were used in this Dataset.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 1,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'studyFactorType',
        displayName: 'Factor Type',
        title: 'Factor Type',
        type: 'TEXT',
        watermark: '',
        description: 'Factors used in the Dataset.',
        multiple: true,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'Age',
          'Biomarkers',
          'Cell Surface Markers',
          'Cell Type/Cell Line',
          'Developmental Stage',
          'Disease State',
          'Drug Susceptibility',
          'Extract Molecule',
          'Genetic Characteristics',
          'Immunoprecipitation Antibody',
          'Organism',
          'Passages',
          'Platform',
          'Sex',
          'Strain',
          'Time Point',
          'Tissue Type',
          'Treatment Compound',
          'Treatment Type',
          'Other'
        ],
        displayFormat: '',
        isRequired: false,
        displayOrder: 2,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      },
      {
        name: 'studyOtherFactorType',
        displayName: 'Other Factor Type',
        title: 'Other Factor Type',
        type: 'TEXT',
        watermark: '',
        description:
          'If Other was selected in Factor Type, list any other factor types that were used in this Dataset.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 3,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'studyAssayOrganism',
        displayName: 'Organism',
        title: 'Organism',
        type: 'TEXT',
        watermark: '',
        description:
          'The taxonomic name of the organism used in the Dataset or from which the  starting biological material derives.',
        multiple: true,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'Arabidopsis thaliana',
          'Bos taurus',
          'Caenorhabditis elegans',
          'Chlamydomonas reinhardtii',
          'Danio rerio (zebrafish)',
          'Dictyostelium discoideum',
          'Drosophila melanogaster',
          'Escherichia coli',
          'Hepatitis C virus',
          'Homo sapiens',
          'Mus musculus',
          'Mycobacterium africanum',
          'Mycobacterium canetti',
          'Mycobacterium tuberculosis',
          'Mycoplasma pneumoniae',
          'Oryza sativa',
          'Plasmodium falciparum',
          'Pneumocystis carinii',
          'Rattus norvegicus',
          "Saccharomyces cerevisiae (brewer's yeast)",
          'Schizosaccharomyces pombe',
          'Takifugu rubripes',
          'Xenopus laevis',
          'Zea mays',
          'Other'
        ],
        displayFormat: '',
        isRequired: false,
        displayOrder: 4,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      },
      {
        name: 'studyAssayOtherOrganism',
        displayName: 'Other Organism',
        title: 'Other Organism',
        type: 'TEXT',
        watermark: '',
        description:
          'If Other was selected in Organism, list any other organisms that were used in this Dataset. Terms from the NCBI Taxonomy are recommended.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 5,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'studyAssayMeasurementType',
        displayName: 'Measurement Type',
        title: 'Measurement Type',
        type: 'TEXT',
        watermark: '',
        description:
          'A term to qualify the endpoint, or what is being measured (e.g. gene expression profiling; protein identification).',
        multiple: true,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'cell counting',
          'cell sorting',
          'clinical chemistry analysis',
          'copy number variation profiling',
          'DNA methylation profiling',
          'DNA methylation profiling (Bisulfite-Seq)',
          'DNA methylation profiling (MeDIP-Seq)',
          'drug susceptibility',
          'environmental gene survey',
          'genome sequencing',
          'hematology',
          'histology',
          'Histone Modification (ChIP-Seq)',
          'loss of heterozygosity profiling',
          'metabolite profiling',
          'metagenome sequencing',
          'protein expression profiling',
          'protein identification',
          'protein-DNA binding site identification',
          'protein-protein interaction detection',
          'protein-RNA binding (RIP-Seq)',
          'SNP analysis',
          'targeted sequencing',
          'transcription factor binding (ChIP-Seq)',
          'transcription factor binding site identification',
          'transcription profiling',
          'transcription profiling (Microarray)',
          'transcription profiling (RNA-Seq)',
          'TRAP translational profiling',
          'Other'
        ],
        displayFormat: '',
        isRequired: false,
        displayOrder: 6,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      },
      {
        name: 'studyAssayOtherMeasurmentType',
        displayName: 'Other Measurement Type',
        title: 'Other Measurement Type',
        type: 'TEXT',
        watermark: '',
        description:
          'If Other was selected in Measurement Type, list any other measurement types that were used. Terms from NCBO Bioportal are recommended.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 7,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'studyAssayTechnologyType',
        displayName: 'Technology Type',
        title: 'Technology Type',
        type: 'TEXT',
        watermark: '',
        description:
          'A term to identify the technology used to perform the measurement (e.g. DNA microarray; mass spectrometry).',
        multiple: true,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'culture based drug susceptibility testing, single concentration',
          'culture based drug susceptibility testing, two concentrations',
          'culture based drug susceptibility testing, three or more concentrations (minimium inhibitory concentration measurement)',
          'DNA microarray',
          'flow cytometry',
          'gel electrophoresis',
          'mass spectrometry',
          'NMR spectroscopy',
          'nucleotide sequencing',
          'protein microarray',
          'real time PCR',
          'no technology required',
          'Other'
        ],
        displayFormat: '',
        isRequired: false,
        displayOrder: 8,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      },
      {
        name: 'studyAssayOtherTechnologyType',
        displayName: 'Other Technology Type',
        title: 'Other Technology Type',
        type: 'TEXT',
        watermark: '',
        description:
          'If Other was selected in Technology Type, list any other technology types that were used in this Dataset.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 9,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'studyAssayPlatform',
        displayName: 'Technology Platform',
        title: 'Technology Platform',
        type: 'TEXT',
        watermark: '',
        description:
          'The manufacturer and name of the technology platform used in the assay (e.g. Bruker AVANCE).',
        multiple: true,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          '210-MS GC Ion Trap (Varian)',
          '220-MS GC Ion Trap (Varian)',
          '225-MS GC Ion Trap (Varian)',
          '240-MS GC Ion Trap (Varian)',
          '300-MS quadrupole GC/MS (Varian)',
          '320-MS LC/MS (Varian)',
          '325-MS LC/MS (Varian)',
          '320-MS GC/MS (Varian)',
          '500-MS LC/MS (Varian)',
          '800D (Jeol)',
          '910-MS TQ-FT (Varian)',
          '920-MS TQ-FT (Varian)',
          '3100 Mass Detector (Waters)',
          '6110 Quadrupole LC/MS (Agilent)',
          '6120 Quadrupole LC/MS (Agilent)',
          '6130 Quadrupole LC/MS (Agilent)',
          '6140 Quadrupole LC/MS (Agilent)',
          '6310 Ion Trap LC/MS (Agilent)',
          '6320 Ion Trap LC/MS (Agilent)',
          '6330 Ion Trap LC/MS (Agilent)',
          '6340 Ion Trap LC/MS (Agilent)',
          '6410 Triple Quadrupole LC/MS (Agilent)',
          '6430 Triple Quadrupole LC/MS (Agilent)',
          '6460 Triple Quadrupole LC/MS (Agilent)',
          '6490 Triple Quadrupole LC/MS (Agilent)',
          '6530 Q-TOF LC/MS (Agilent)',
          '6540 Q-TOF LC/MS (Agilent)',
          '6210 TOF LC/MS (Agilent)',
          '6220 TOF LC/MS (Agilent)',
          '6230 TOF LC/MS (Agilent)',
          '7000B Triple Quadrupole GC/MS (Agilent)',
          'AccuTO DART (Jeol)',
          'AccuTOF GC (Jeol)',
          'AccuTOF LC (Jeol)',
          'ACQUITY SQD (Waters)',
          'ACQUITY TQD (Waters)',
          'Agilent',
          'Agilent 5975E GC/MSD (Agilent)',
          'Agilent 5975T LTM GC/MSD (Agilent)',
          '5975C Series GC/MSD (Agilent)',
          'Affymetrix',
          'amaZon ETD ESI Ion Trap (Bruker)',
          'amaZon X ESI Ion Trap (Bruker)',
          'apex-ultra hybrid Qq-FTMS (Bruker)',
          'API 2000 (AB Sciex)',
          'API 3200 (AB Sciex)',
          'API 3200 QTRAP (AB Sciex)',
          'API 4000 (AB Sciex)',
          'API 4000 QTRAP (AB Sciex)',
          'API 5000 (AB Sciex)',
          'API 5500 (AB Sciex)',
          'API 5500 QTRAP (AB Sciex)',
          'Applied Biosystems Group (ABI)',
          'AQI Biosciences',
          'Atmospheric Pressure GC (Waters)',
          'autoflex III MALDI-TOF MS (Bruker)',
          'autoflex speed(Bruker)',
          'AutoSpec Premier (Waters)',
          'AXIMA Mega TOF (Shimadzu)',
          'AXIMA Performance MALDI TOF/TOF (Shimadzu)',
          'A-10 Analyzer (Apogee)',
          'A-40-MiniFCM (Apogee)',
          'Bactiflow (Chemunex SA)',
          'Base4innovation',
          'BD BACTEC MGIT 320',
          'BD BACTEC MGIT 960',
          'BD Radiometric BACTEC 460TB',
          'BioNanomatrix',
          'Cell Lab Quanta SC (Becman Coulter)',
          'Clarus 560 D GC/MS (PerkinElmer)',
          'Clarus 560 S GC/MS (PerkinElmer)',
          'Clarus 600 GC/MS (PerkinElmer)',
          'Complete Genomics',
          'Cyan (Dako Cytomation)',
          'CyFlow ML (Partec)',
          'Cyow SL (Partec)',
          'CyFlow SL3 (Partec)',
          'CytoBuoy (Cyto Buoy Inc)',
          'CytoSence (Cyto Buoy Inc)',
          'CytoSub (Cyto Buoy Inc)',
          'Danaher',
          'DFS (Thermo Scientific)',
          'Exactive(Thermo Scientific)',
          'FACS Canto (Becton Dickinson)',
          'FACS Canto2 (Becton Dickinson)',
          'FACS Scan (Becton Dickinson)',
          'FC 500 (Becman Coulter)',
          'GCmate II GC/MS (Jeol)',
          'GCMS-QP2010 Plus (Shimadzu)',
          'GCMS-QP2010S Plus (Shimadzu)',
          'GCT Premier (Waters)',
          'GENEQ',
          'Genome Corp.',
          'GenoVoxx',
          'GnuBio',
          'Guava EasyCyte Mini (Millipore)',
          'Guava EasyCyte Plus (Millipore)',
          'Guava Personal Cell Analysis (Millipore)',
          'Guava Personal Cell Analysis-96 (Millipore)',
          'Helicos BioSciences',
          'Illumina',
          'Indirect proportion method on LJ medium',
          'Indirect proportion method on Middlebrook Agar 7H9',
          'Indirect proportion method on Middlebrook Agar 7H10',
          'Indirect proportion method on Middlebrook Agar 7H11',
          'inFlux Analyzer (Cytopeia)',
          'Intelligent Bio-Systems',
          'ITQ 700 (Thermo Scientific)',
          'ITQ 900 (Thermo Scientific)',
          'ITQ 1100 (Thermo Scientific)',
          'JMS-53000 SpiralTOF (Jeol)',
          'LaserGen',
          'LCMS-2020 (Shimadzu)',
          'LCMS-2010EV (Shimadzu)',
          'LCMS-IT-TOF (Shimadzu)',
          'Li-Cor',
          'Life Tech',
          'LightSpeed Genomics',
          'LCT Premier XE (Waters)',
          'LCQ Deca XP MAX (Thermo Scientific)',
          'LCQ Fleet (Thermo Scientific)',
          'LXQ (Thermo Scientific)',
          'LTQ Classic (Thermo Scientific)',
          'LTQ XL (Thermo Scientific)',
          'LTQ Velos (Thermo Scientific)',
          'LTQ Orbitrap Classic (Thermo Scientific)',
          'LTQ Orbitrap XL (Thermo Scientific)',
          'LTQ Orbitrap Discovery (Thermo Scientific)',
          'LTQ Orbitrap Velos (Thermo Scientific)',
          'Luminex 100 (Luminex)',
          'Luminex 200 (Luminex)',
          'MACS Quant (Miltenyi)',
          'MALDI SYNAPT G2 HDMS (Waters)',
          'MALDI SYNAPT G2 MS (Waters)',
          'MALDI SYNAPT HDMS (Waters)',
          'MALDI SYNAPT MS (Waters)',
          'MALDI micro MX (Waters)',
          'maXis (Bruker)',
          'maXis G4 (Bruker)',
          'microflex LT MALDI-TOF MS (Bruker)',
          'microflex LRF MALDI-TOF MS (Bruker)',
          'microflex III MALDI-TOF MS (Bruker)',
          'micrOTOF II ESI TOF (Bruker)',
          'micrOTOF-Q II ESI-Qq-TOF (Bruker)',
          'microplate Alamar Blue (resazurin) colorimetric method',
          'Mstation (Jeol)',
          'MSQ Plus (Thermo Scientific)',
          'NABsys',
          'Nanophotonics Biosciences',
          'Network Biosystems',
          'Nimblegen',
          'Oxford Nanopore Technologies',
          'Pacific Biosciences',
          'Population Genetics Technologies',
          'Q1000GC UltraQuad (Jeol)',
          'Quattro micro API (Waters)',
          'Quattro micro GC (Waters)',
          'Quattro Premier XE (Waters)',
          'QSTAR (AB Sciex)',
          'Reveo',
          'Roche',
          'Seirad',
          'solariX hybrid Qq-FTMS (Bruker)',
          'Somacount (Bently Instruments)',
          'SomaScope (Bently Instruments)',
          'SYNAPT G2 HDMS (Waters)',
          'SYNAPT G2 MS (Waters)',
          'SYNAPT HDMS (Waters)',
          'SYNAPT MS (Waters)',
          'TripleTOF 5600 (AB Sciex)',
          'TSQ Quantum Ultra (Thermo Scientific)',
          'TSQ Quantum Access (Thermo Scientific)',
          'TSQ Quantum Access MAX (Thermo Scientific)',
          'TSQ Quantum Discovery MAX (Thermo Scientific)',
          'TSQ Quantum GC (Thermo Scientific)',
          'TSQ Quantum XLS (Thermo Scientific)',
          'TSQ Vantage (Thermo Scientific)',
          'ultrafleXtreme MALDI-TOF MS (Bruker)',
          'VisiGen Biotechnologies',
          'Xevo G2 QTOF (Waters)',
          'Xevo QTof MS (Waters)',
          'Xevo TQ MS (Waters)',
          'Xevo TQ-S (Waters)',
          'Other'
        ],
        displayFormat: '',
        isRequired: false,
        displayOrder: 10,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      },
      {
        name: 'studyAssayOtherPlatform',
        displayName: 'Other Technology Platform',
        title: 'Other Technology Platform',
        type: 'TEXT',
        watermark: '',
        description:
          'If Other was selected in Technology Platform, list any other technology platforms that were used in this Dataset.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 11,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'studyAssayCellType',
        displayName: 'Cell Type',
        title: 'Cell Type',
        type: 'TEXT',
        watermark: '',
        description: 'The name of the cell line from which the source or sample derives.',
        multiple: true,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 12,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'journalVolume',
        displayName: 'Journal Volume',
        title: 'Volume',
        type: 'TEXT',
        watermark: '',
        description: 'The journal volume which this Dataset is associated with (e.g., Volume 4).',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 1,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'journalIssue',
        displayName: 'Journal Issue',
        title: 'Issue',
        type: 'TEXT',
        watermark: '',
        description:
          'The journal issue number which this Dataset is associated with (e.g., Number 2, Autumn).',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 2,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'journalPubDate',
        displayName: 'Journal Publication Date',
        title: 'Publication Date',
        type: 'DATE',
        watermark: 'YYYY or YYYY-MM or YYYY-MM-DD',
        description:
          'The publication date for this journal volume/issue, which this Dataset is associated with (e.g., 1999).',
        multiple: false,
        isControlledVocabulary: false,
        displayFormat: '',
        isRequired: false,
        displayOrder: 3,
        typeClass: 'primitive',
        displayOnCreate: false
      },
      {
        name: 'journalArticleType',
        displayName: 'Type of Article',
        title: 'Type of Article',
        type: 'TEXT',
        watermark: '',
        description:
          'Indicates what kind of article this is, for example, a research article, a commentary, a book or product review, a case report, a calendar, etc (based on JATS). ',
        multiple: false,
        isControlledVocabulary: true,
        controlledVocabularyValues: [
          'abstract',
          'addendum',
          'announcement',
          'article-commentary',
          'book review',
          'books received',
          'brief report',
          'calendar',
          'case report',
          'collection',
          'correction',
          'data paper',
          'discussion',
          'dissertation',
          'editorial',
          'in brief',
          'introduction',
          'letter',
          'meeting report',
          'news',
          'obituary',
          'oration',
          'partial retraction',
          'product review',
          'rapid communication',
          'reply',
          'reprint',
          'research article',
          'retraction',
          'review article',
          'translation',
          'other'
        ],
        displayFormat: '',
        isRequired: false,
        displayOrder: 4,
        typeClass: 'controlledVocabulary',
        displayOnCreate: false
      }
    ]
  }
}
