import { MetadataBlockInfo } from '../../../../../src/metadata-block-info/domain/models/MetadataBlockInfo'

export class GeospatialMetadataBlockInfoMother {
  static get(): MetadataBlockInfo {
    return {
      id: 2,
      name: 'geospatial',
      displayName: 'Geospatial Metadata',
      displayOnCreate: false,
      metadataFields: {
        geographicCoverage: {
          name: 'geographicCoverage',
          displayName: 'Geographic Coverage',
          title: 'Geographic Coverage',
          type: 'NONE',
          watermark: '',
          description:
            'Information on the geographic coverage of the data. Includes the total geographic scope of the data.',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 0,
          typeClass: 'compound',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false,
          childMetadataFields: {
            country: {
              name: 'country',
              displayName: 'Geographic Coverage Country / Nation',
              title: 'Country / Nation',
              type: 'TEXT',
              watermark: '',
              description: 'The country or nation that the Dataset is about.',
              multiple: false,
              isControlledVocabulary: true,
              controlledVocabularyValues: [
                'Afghanistan',
                'Albania',
                'Algeria',
                'American Samoa',
                'Andorra',
                'Angola',
                'Anguilla',
                'Antarctica',
                'Antigua and Barbuda',
                'Argentina',
                'Armenia',
                'Aruba',
                'Australia',
                'Austria',
                'Azerbaijan',
                'Bahamas',
                'Bahrain',
                'Bangladesh',
                'Barbados',
                'Belarus',
                'Belgium',
                'Belize',
                'Benin',
                'Bermuda',
                'Bhutan',
                'Bolivia, Plurinational State of',
                'Bonaire, Sint Eustatius and Saba',
                'Bosnia and Herzegovina',
                'Botswana',
                'Bouvet Island',
                'Brazil',
                'British Indian Ocean Territory',
                'Brunei Darussalam',
                'Bulgaria',
                'Burkina Faso',
                'Burundi',
                'Cambodia',
                'Cameroon',
                'Canada',
                'Cape Verde',
                'Cayman Islands',
                'Central African Republic',
                'Chad',
                'Chile',
                'China',
                'Christmas Island',
                'Cocos (Keeling) Islands',
                'Colombia',
                'Comoros',
                'Congo',
                'Congo, the Democratic Republic of the',
                'Cook Islands',
                'Costa Rica',
                'Croatia',
                'Cuba',
                'Curaçao',
                'Cyprus',
                'Czech Republic',
                "Côte d'Ivoire",
                'Denmark',
                'Djibouti',
                'Dominica',
                'Dominican Republic',
                'Ecuador',
                'Egypt',
                'El Salvador',
                'Equatorial Guinea',
                'Eritrea',
                'Estonia',
                'Ethiopia',
                'Falkland Islands (Malvinas)',
                'Faroe Islands',
                'Fiji',
                'Finland',
                'France',
                'French Guiana',
                'French Polynesia',
                'French Southern Territories',
                'Gabon',
                'Gambia',
                'Georgia',
                'Germany',
                'Ghana',
                'Gibraltar',
                'Greece',
                'Greenland',
                'Grenada',
                'Guadeloupe',
                'Guam',
                'Guatemala',
                'Guernsey',
                'Guinea',
                'Guinea-Bissau',
                'Guyana',
                'Haiti',
                'Heard Island and Mcdonald Islands',
                'Holy See (Vatican City State)',
                'Honduras',
                'Hong Kong',
                'Hungary',
                'Iceland',
                'India',
                'Indonesia',
                'Iran, Islamic Republic of',
                'Iraq',
                'Ireland',
                'Isle of Man',
                'Israel',
                'Italy',
                'Jamaica',
                'Japan',
                'Jersey',
                'Jordan',
                'Kazakhstan',
                'Kenya',
                'Kiribati',
                "Korea, Democratic People's Republic of",
                'Korea, Republic of',
                'Kuwait',
                'Kyrgyzstan',
                "Lao People's Democratic Republic",
                'Latvia',
                'Lebanon',
                'Lesotho',
                'Liberia',
                'Libya',
                'Liechtenstein',
                'Lithuania',
                'Luxembourg',
                'Macao',
                'Macedonia, the Former Yugoslav Republic of',
                'Madagascar',
                'Malawi',
                'Malaysia',
                'Maldives',
                'Mali',
                'Malta',
                'Marshall Islands',
                'Martinique',
                'Mauritania',
                'Mauritius',
                'Mayotte',
                'Mexico',
                'Micronesia, Federated States of',
                'Moldova, Republic of',
                'Monaco',
                'Mongolia',
                'Montenegro',
                'Montserrat',
                'Morocco',
                'Mozambique',
                'Myanmar',
                'Namibia',
                'Nauru',
                'Nepal',
                'Netherlands',
                'New Caledonia',
                'New Zealand',
                'Nicaragua',
                'Niger',
                'Nigeria',
                'Niue',
                'Norfolk Island',
                'Northern Mariana Islands',
                'Norway',
                'Oman',
                'Pakistan',
                'Palau',
                'Palestine, State of',
                'Panama',
                'Papua New Guinea',
                'Paraguay',
                'Peru',
                'Philippines',
                'Pitcairn',
                'Poland',
                'Portugal',
                'Puerto Rico',
                'Qatar',
                'Romania',
                'Russian Federation',
                'Rwanda',
                'Réunion',
                'Saint Barthélemy',
                'Saint Helena, Ascension and Tristan da Cunha',
                'Saint Kitts and Nevis',
                'Saint Lucia',
                'Saint Martin (French part)',
                'Saint Pierre and Miquelon',
                'Saint Vincent and the Grenadines',
                'Samoa',
                'San Marino',
                'Sao Tome and Principe',
                'Saudi Arabia',
                'Senegal',
                'Serbia',
                'Seychelles',
                'Sierra Leone',
                'Singapore',
                'Sint Maarten (Dutch part)',
                'Slovakia',
                'Slovenia',
                'Solomon Islands',
                'Somalia',
                'South Africa',
                'South Georgia and the South Sandwich Islands',
                'South Sudan',
                'Spain',
                'Sri Lanka',
                'Sudan',
                'Suriname',
                'Svalbard and Jan Mayen',
                'Swaziland',
                'Sweden',
                'Switzerland',
                'Syrian Arab Republic',
                'Taiwan, Province of China',
                'Tajikistan',
                'Tanzania, United Republic of',
                'Thailand',
                'Timor-Leste',
                'Togo',
                'Tokelau',
                'Tonga',
                'Trinidad and Tobago',
                'Tunisia',
                'Turkey',
                'Turkmenistan',
                'Turks and Caicos Islands',
                'Tuvalu',
                'Uganda',
                'Ukraine',
                'United Arab Emirates',
                'United Kingdom',
                'United States',
                'United States Minor Outlying Islands',
                'Uruguay',
                'Uzbekistan',
                'Vanuatu',
                'Venezuela, Bolivarian Republic of',
                'Viet Nam',
                'Virgin Islands, British',
                'Virgin Islands, U.S.',
                'Wallis and Futuna',
                'Western Sahara',
                'Yemen',
                'Zambia',
                'Zimbabwe',
                'Åland Islands'
              ],
              displayFormat: '#VALUE, ',
              isRequired: false,
              displayOrder: 1,
              typeClass: 'controlledVocabulary',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            },
            state: {
              name: 'state',
              displayName: 'Geographic Coverage State / Province',
              title: 'State / Province',
              type: 'TEXT',
              watermark: '',
              description:
                'The state or province that the Dataset is about. Use GeoNames for correct spelling and avoid abbreviations.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '#VALUE, ',
              isRequired: false,
              displayOrder: 2,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            },
            city: {
              name: 'city',
              displayName: 'Geographic Coverage City',
              title: 'City',
              type: 'TEXT',
              watermark: '',
              description:
                'The name of the city that the Dataset is about. Use GeoNames for correct spelling and avoid abbreviations.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '#VALUE, ',
              isRequired: false,
              displayOrder: 3,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            },
            otherGeographicCoverage: {
              name: 'otherGeographicCoverage',
              displayName: 'Geographic Coverage Other',
              title: 'Other',
              type: 'TEXT',
              watermark: '',
              description: 'Other information on the geographic coverage of the data.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '#VALUE, ',
              isRequired: false,
              displayOrder: 4,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            }
          }
        },
        geographicUnit: {
          name: 'geographicUnit',
          displayName: 'Geographic Unit',
          title: 'Geographic Unit',
          type: 'TEXT',
          watermark: '',
          description:
            'Lowest level of geographic aggregation covered by the Dataset, e.g., village, county, region.',
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 5,
          typeClass: 'primitive',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false
        },
        geographicBoundingBox: {
          name: 'geographicBoundingBox',
          displayName: 'Geographic Bounding Box',
          title: 'Geographic Bounding Box',
          type: 'NONE',
          watermark: '',
          description:
            "The fundamental geometric description for any Dataset that models geography is the geographic bounding box. It describes the minimum box, defined by west and east longitudes and north and south latitudes, which includes the largest geographic extent of the  Dataset's geographic coverage. This element is used in the first pass of a coordinate-based search. Inclusion of this element in the codebook is recommended, but is required if the bound polygon box is included. ",
          multiple: true,
          isControlledVocabulary: false,
          displayFormat: '',
          isRequired: false,
          displayOrder: 6,
          typeClass: 'compound',
          displayOnCreate: false,
          isAdvancedSearchFieldType: false,
          childMetadataFields: {
            westLongitude: {
              name: 'westLongitude',
              displayName: 'Geographic Bounding Box Westernmost (Left) Longitude',
              title: 'Westernmost (Left) Longitude',
              type: 'TEXT',
              watermark: '',
              description:
                'Westernmost coordinate delimiting the geographic extent of the Dataset. A valid range of values,  expressed in decimal degrees, is -180.0 <= West  Bounding Longitude Value <= 180.0.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '',
              isRequired: false,
              displayOrder: 7,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            },
            eastLongitude: {
              name: 'eastLongitude',
              displayName: 'Geographic Bounding Box Easternmost (Right) Longitude',
              title: 'Easternmost (Right) Longitude',
              type: 'TEXT',
              watermark: '',
              description:
                'Easternmost coordinate delimiting the geographic extent of the Dataset. A valid range of values,  expressed in decimal degrees, is -180.0 <= East Bounding Longitude Value <= 180.0.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '',
              isRequired: false,
              displayOrder: 8,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            },
            northLatitude: {
              name: 'northLatitude',
              displayName: 'Geographic Bounding Box Northernmost (Top) Latitude',
              title: 'Northernmost (Top) Latitude',
              type: 'TEXT',
              watermark: '',
              description:
                'Northernmost coordinate delimiting the geographic extent of the Dataset. A valid range of values,  expressed in decimal degrees, is -90.0 <= North Bounding Latitude Value <= 90.0.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '',
              isRequired: false,
              displayOrder: 9,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            },
            southLatitude: {
              name: 'southLatitude',
              displayName: 'Geographic Bounding Box Southernmost (Bottom) Latitude',
              title: 'Southernmost (Bottom) Latitude',
              type: 'TEXT',
              watermark: '',
              description:
                'Southernmost coordinate delimiting the geographic extent of the Dataset. A valid range of values,  expressed in decimal degrees, is -90.0 <= South Bounding Latitude Value <= 90.0.',
              multiple: false,
              isControlledVocabulary: false,
              displayFormat: '',
              isRequired: false,
              displayOrder: 10,
              typeClass: 'primitive',
              displayOnCreate: false,
              isAdvancedSearchFieldType: false
            }
          }
        }
      }
    }
  }
}
