import {
  MetadataBlockInfo,
  MetadataBlockInfo2
} from '../../../../../src/metadata-block-info/domain/models/MetadataBlockInfo'
import { MetadataBlockName } from '../../../../../src/dataset/domain/models/Dataset'

export class MetadataBlockInfoMother {
  static create(props?: Partial<MetadataBlockInfo>): MetadataBlockInfo {
    return {
      name: MetadataBlockName.CITATION,
      fields: {
        alternativePersistentId: { displayFormat: '' },
        publicationDate: { displayFormat: '' },
        citationDate: { displayFormat: '' },
        title: { displayFormat: '' },
        subject: { displayFormat: ';' },
        author: { displayFormat: '' },
        authorName: { displayFormat: '#VALUE' },
        authorAffiliation: { displayFormat: '(#VALUE)' },
        authorIdentifierScheme: { displayFormat: '- #VALUE:' },
        authorIdentifier: { displayFormat: '[#VALUE](https://orcid.org/#VALUE)' },
        datasetContact: { displayFormat: '#VALUE' },
        datasetContactName: { displayFormat: '#VALUE' },
        datasetContactAffiliation: { displayFormat: '(#VALUE)' },
        datasetContactEmail: { displayFormat: '[#VALUE](mailto:#VALUE)' },
        dsDescription: { displayFormat: '' },
        dsDescriptionValue: { displayFormat: '#VALUE' },
        producerURL: { displayFormat: '[#VALUE](#VALUE)' },
        producerLogoURL: { displayFormat: '![#NAME](#VALUE)' },
        dateOfCollectionStart: { displayFormat: '#NAME: #VALUE ' }
      },
      ...props
    }
  }

  static getByCollectionIdResponse(): MetadataBlockInfo2[] {
    return [
      {
        id: 1,
        displayName: 'Citation Metadatata',
        name: MetadataBlockName.CITATION,
        displayOnCreate: true,
        metadataFields: {
          title: {
            name: 'title',
            displayName: 'Title',
            title: 'Title',
            type: 'TEXT',
            typeClass: 'primitive',
            watermark: '',
            description: 'The main title of the Dataset',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOnCreate: true,
            displayOrder: 0
          },
          subtitle: {
            name: 'subtitle',
            displayName: 'Subtitle',
            title: 'Subtitle',
            type: 'TEXT',
            typeClass: 'primitive',
            watermark: '',
            description:
              'A secondary title that amplifies or states certain limitations on the main title',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            displayOnCreate: true,
            isRequired: false,
            displayOrder: 1
          },
          author: {
            name: 'author',
            displayName: 'Author',
            title: 'Author',
            type: 'NONE',
            typeClass: 'compound',
            watermark: '',
            description: 'The entity, e.g. a person or organization, that created the Dataset',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 7,
            displayOnCreate: true,
            childMetadataFields: {
              authorName: {
                name: 'authorName',
                displayName: 'Author Name',
                title: 'Name',
                type: 'TEXT',
                typeClass: 'primitive',
                watermark: '1) Family Name, Given Name or 2) Organization XYZ',
                description:
                  "The name of the author, such as the person's name or the name of an organization",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: true,
                displayOnCreate: true,
                displayOrder: 8
              },
              authorIdentifierScheme: {
                name: 'authorIdentifierScheme',
                displayName: 'Author Identifier Type',
                title: 'Identifier Type',
                type: 'TEXT',
                typeClass: 'controlledVocabulary',
                watermark: '',
                description:
                  'The type of identifier that uniquely identifies the author (e.g. ORCID, ISNI)',
                multiple: false,
                isControlledVocabulary: true,
                displayFormat: '- #VALUE:',
                isRequired: false,
                displayOnCreate: true,
                displayOrder: 10,
                controlledVocabularyValues: [
                  'ORCID',
                  'ISNI',
                  'LCNA',
                  'VIAF',
                  'GND',
                  'DAI',
                  'ResearcherID',
                  'ScopusID'
                ]
              }
            }
          },
          notesText: {
            name: 'notesText',
            displayName: 'Notes',
            title: 'Notes',
            type: 'TEXTBOX',
            typeClass: 'primitive',
            watermark: '',
            description: 'Additional information about the Dataset',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 33,
            displayOnCreate: true
          },
          producerURL: {
            name: 'producerURL',
            displayName: 'Producer URL',
            title: 'Producer URL',
            type: 'URL',
            typeClass: 'primitive',
            watermark: 'https://',
            description: "The URL of the producer's website",
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '<a href="#VALUE" target="_blank" rel="noopener">#VALUE</a>',
            isRequired: false,
            displayOnCreate: true,
            displayOrder: 39
          },
          datasetContactEmail: {
            name: 'datasetContactEmail',
            displayName: 'Point of Contact E-mail',
            title: 'E-mail',
            type: 'EMAIL',
            typeClass: 'primitive',
            watermark: 'name@email.xyz',
            description: "The point of contact's email address",
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '#EMAIL',
            isRequired: true,
            displayOnCreate: true,
            displayOrder: 15
          },
          dsDescriptionDate: {
            name: 'dsDescriptionDate',
            displayName: 'Description Date',
            title: 'Description Date',
            type: 'DATE',
            typeClass: 'primitive',
            watermark: 'YYYY-MM-DD',
            description:
              'The date when the description was added to the Dataset. If the Dataset contains more than one description, e.g. the data producer supplied one description and the data repository supplied another, this date is used to distinguish between the descriptions',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '(#VALUE)',
            isRequired: false,
            displayOnCreate: true,
            displayOrder: 18
          },
          floatSomething: {
            name: 'floatSomething',
            displayName: 'Float Something',
            title: 'Float Something',
            type: 'FLOAT',
            typeClass: 'primitive',
            watermark: 'Enter a floating-point number.',
            description: 'The central wavelength of the spectral bandpass, in meters.',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOnCreate: true,
            displayOrder: 8
          },
          integerSomething: {
            name: 'integerSomething',
            displayName: 'Integer Something',
            title: 'Integer Something',
            type: 'INT',
            typeClass: 'primitive',
            watermark: 'Enter an integer.',
            description: 'The total number of objects, catalog entries, etc., in the data object.',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOnCreate: true,
            displayOrder: 18
          }
        }
      },
      {
        id: 2,
        displayName: 'Geospatial Metadata',
        name: MetadataBlockName.GEOSPATIAL,
        displayOnCreate: true,
        metadataFields: {
          geographicCoverage: {
            name: 'geographicCoverage',
            displayName: 'Geographic Coverage',
            title: 'Geographic Coverage',
            type: 'NONE',
            typeClass: 'compound',
            watermark: '',
            description:
              'Information on the geographic coverage of the data. Includes the total geographic scope of the data.',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 0,
            displayOnCreate: true,
            childMetadataFields: {
              country: {
                name: 'country',
                displayName: 'Geographic Coverage Country / Nation',
                title: 'Country / Nation',
                type: 'TEXT',
                typeClass: 'controlledVocabulary',
                watermark: '',
                description: 'The country or nation that the Dataset is about.',
                multiple: false,
                isControlledVocabulary: true,
                displayFormat: '#VALUE, ',
                isRequired: false,
                displayOrder: 1,
                displayOnCreate: true,
                controlledVocabularyValues: [
                  'Afghanistan',
                  'Albania',
                  'Algeria',
                  'American Samoa',
                  'Andorra',
                  'Angola',
                  'Anguilla',
                  'Antarctica',
                  'Antigua and Barbuda',
                  'Argentina',
                  'Armenia',
                  'Aruba',
                  'Australia',
                  'Austria',
                  'Azerbaijan',
                  'Bahamas',
                  'Bahrain',
                  'Bangladesh',
                  'Barbados',
                  'Belarus',
                  'Belgium',
                  'Belize',
                  'Benin',
                  'Bermuda',
                  'Bhutan',
                  'Bolivia, Plurinational State of',
                  'Bonaire, Sint Eustatius and Saba',
                  'Bosnia and Herzegovina',
                  'Botswana',
                  'Bouvet Island',
                  'Brazil',
                  'British Indian Ocean Territory',
                  'Brunei Darussalam',
                  'Bulgaria',
                  'Burkina Faso',
                  'Burundi',
                  'Cambodia',
                  'Cameroon',
                  'Canada',
                  'Cape Verde',
                  'Cayman Islands',
                  'Central African Republic',
                  'Chad',
                  'Chile',
                  'China',
                  'Christmas Island',
                  'Cocos (Keeling) Islands',
                  'Colombia',
                  'Comoros',
                  'Congo',
                  'Congo, the Democratic Republic of the',
                  'Cook Islands',
                  'Costa Rica',
                  'Croatia',
                  'Cuba',
                  'Curaçao',
                  'Cyprus',
                  'Czech Republic',
                  "Côte d'Ivoire",
                  'Denmark',
                  'Djibouti',
                  'Dominica',
                  'Dominican Republic',
                  'Ecuador',
                  'Egypt',
                  'El Salvador',
                  'Equatorial Guinea',
                  'Eritrea',
                  'Estonia',
                  'Ethiopia',
                  'Falkland Islands (Malvinas)',
                  'Faroe Islands',
                  'Fiji',
                  'Finland',
                  'France',
                  'French Guiana',
                  'French Polynesia',
                  'French Southern Territories',
                  'Gabon',
                  'Gambia',
                  'Georgia',
                  'Germany',
                  'Ghana',
                  'Gibraltar',
                  'Greece',
                  'Greenland',
                  'Grenada',
                  'Guadeloupe',
                  'Guam',
                  'Guatemala',
                  'Guernsey',
                  'Guinea',
                  'Guinea-Bissau',
                  'Guyana',
                  'Haiti',
                  'Heard Island and Mcdonald Islands',
                  'Holy See (Vatican City State)',
                  'Honduras',
                  'Hong Kong',
                  'Hungary',
                  'Iceland',
                  'India',
                  'Indonesia',
                  'Iran, Islamic Republic of',
                  'Iraq',
                  'Ireland',
                  'Isle of Man',
                  'Israel',
                  'Italy',
                  'Jamaica',
                  'Japan',
                  'Jersey',
                  'Jordan',
                  'Kazakhstan',
                  'Kenya',
                  'Kiribati',
                  "Korea, Democratic People's Republic of",
                  'Korea, Republic of',
                  'Kuwait',
                  'Kyrgyzstan',
                  "Lao People's Democratic Republic",
                  'Latvia',
                  'Lebanon',
                  'Lesotho',
                  'Liberia',
                  'Libya',
                  'Liechtenstein',
                  'Lithuania',
                  'Luxembourg',
                  'Macao',
                  'Macedonia, the Former Yugoslav Republic of',
                  'Madagascar',
                  'Malawi',
                  'Malaysia',
                  'Maldives',
                  'Mali',
                  'Malta',
                  'Marshall Islands',
                  'Martinique',
                  'Mauritania',
                  'Mauritius',
                  'Mayotte',
                  'Mexico',
                  'Micronesia, Federated States of',
                  'Moldova, Republic of',
                  'Monaco',
                  'Mongolia',
                  'Montenegro',
                  'Montserrat',
                  'Morocco',
                  'Mozambique',
                  'Myanmar',
                  'Namibia',
                  'Nauru',
                  'Nepal',
                  'Netherlands',
                  'New Caledonia',
                  'New Zealand',
                  'Nicaragua',
                  'Niger',
                  'Nigeria',
                  'Niue',
                  'Norfolk Island',
                  'Northern Mariana Islands',
                  'Norway',
                  'Oman',
                  'Pakistan',
                  'Palau',
                  'Palestine, State of',
                  'Panama',
                  'Papua New Guinea',
                  'Paraguay',
                  'Peru',
                  'Philippines',
                  'Pitcairn',
                  'Poland',
                  'Portugal',
                  'Puerto Rico',
                  'Qatar',
                  'Romania',
                  'Russian Federation',
                  'Rwanda',
                  'Réunion',
                  'Saint Barthélemy',
                  'Saint Helena, Ascension and Tristan da Cunha',
                  'Saint Kitts and Nevis',
                  'Saint Lucia',
                  'Saint Martin (French part)',
                  'Saint Pierre and Miquelon',
                  'Saint Vincent and the Grenadines',
                  'Samoa',
                  'San Marino',
                  'Sao Tome and Principe',
                  'Saudi Arabia',
                  'Senegal',
                  'Serbia',
                  'Seychelles',
                  'Sierra Leone',
                  'Singapore',
                  'Sint Maarten (Dutch part)',
                  'Slovakia',
                  'Slovenia',
                  'Solomon Islands',
                  'Somalia',
                  'South Africa',
                  'South Georgia and the South Sandwich Islands',
                  'South Sudan',
                  'Spain',
                  'Sri Lanka',
                  'Sudan',
                  'Suriname',
                  'Svalbard and Jan Mayen',
                  'Swaziland',
                  'Sweden',
                  'Switzerland',
                  'Syrian Arab Republic',
                  'Taiwan, Province of China',
                  'Tajikistan',
                  'Tanzania, United Republic of',
                  'Thailand',
                  'Timor-Leste',
                  'Togo',
                  'Tokelau',
                  'Tonga',
                  'Trinidad and Tobago',
                  'Tunisia',
                  'Turkey',
                  'Turkmenistan',
                  'Turks and Caicos Islands',
                  'Tuvalu',
                  'Uganda',
                  'Ukraine',
                  'United Arab Emirates',
                  'United Kingdom',
                  'United States',
                  'United States Minor Outlying Islands',
                  'Uruguay',
                  'Uzbekistan',
                  'Vanuatu',
                  'Venezuela, Bolivarian Republic of',
                  'Viet Nam',
                  'Virgin Islands, British',
                  'Virgin Islands, U.S.',
                  'Wallis and Futuna',
                  'Western Sahara',
                  'Yemen',
                  'Zambia',
                  'Zimbabwe',
                  'Åland Islands'
                ]
              },
              state: {
                name: 'state',
                displayName: 'Geographic Coverage State / Province',
                title: 'State / Province',
                type: 'TEXT',
                typeClass: 'primitive',
                watermark: '',
                description:
                  'The state or province that the Dataset is about. Use GeoNames for correct spelling and avoid abbreviations.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE, ',
                isRequired: false,
                displayOnCreate: true,
                displayOrder: 2
              },
              city: {
                name: 'city',
                displayName: 'Geographic Coverage City',
                title: 'City',
                type: 'TEXT',
                typeClass: 'primitive',
                watermark: '',
                description:
                  'The name of the city that the Dataset is about. Use GeoNames for correct spelling and avoid abbreviations.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE, ',
                isRequired: false,
                displayOnCreate: true,
                displayOrder: 3
              },
              otherGeographicCoverage: {
                name: 'otherGeographicCoverage',
                displayName: 'Geographic Coverage Other',
                title: 'Other',
                type: 'TEXT',
                typeClass: 'primitive',
                watermark: '',
                description: 'Other information on the geographic coverage of the data.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE, ',
                isRequired: false,
                displayOnCreate: true,
                displayOrder: 4
              }
            }
          }
        }
      }
    ]
  }
}
