import {
  MetadataBlockInfoDisplayFormat,
  MetadataBlockInfo
} from '../../../../../src/metadata-block-info/domain/models/MetadataBlockInfo'
import { MetadataBlockName } from '../../../../../src/dataset/domain/models/Dataset'

export class MetadataBlockInfoMother {
  static create(props?: Partial<MetadataBlockInfoDisplayFormat>): MetadataBlockInfoDisplayFormat {
    return {
      name: MetadataBlockName.CITATION,
      fields: {
        alternativePersistentId: { displayFormat: '' },
        publicationDate: { displayFormat: '' },
        citationDate: { displayFormat: '' },
        title: { displayFormat: '' },
        subject: { displayFormat: ';' },
        author: { displayFormat: '' },
        authorName: { displayFormat: '#VALUE' },
        authorAffiliation: { displayFormat: '(#VALUE)' },
        authorIdentifierScheme: { displayFormat: '- #VALUE:' },
        authorIdentifier: { displayFormat: '[#VALUE](https://orcid.org/#VALUE)' },
        datasetContact: { displayFormat: '#VALUE' },
        datasetContactName: { displayFormat: '#VALUE' },
        datasetContactAffiliation: { displayFormat: '(#VALUE)' },
        datasetContactEmail: { displayFormat: '[#VALUE](mailto:#VALUE)' },
        dsDescription: { displayFormat: '' },
        dsDescriptionValue: { displayFormat: '#VALUE' },
        producerURL: { displayFormat: '[#VALUE](#VALUE)' },
        producerLogoURL: { displayFormat: '![#NAME](#VALUE)' },
        dateOfCollectionStart: { displayFormat: '#NAME: #VALUE ' }
      },
      ...props
    }
  }

  static getByCollectionIdDisplayedOnCreateTrue(block?: MetadataBlockInfo): MetadataBlockInfo[] {
    return [
      {
        id: 1,
        name: 'citation',
        displayName: 'Citation Metadata',
        displayOnCreate: true,
        metadataFields: {
          title: {
            name: 'title',
            displayName: 'Title',
            title: 'Title',
            type: 'TEXT',
            watermark: '',
            description: 'The main title of the Dataset',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 0,
            typeClass: 'primitive',
            displayOnCreate: true
          },
          author: {
            name: 'author',
            displayName: 'Author',
            title: 'Author',
            type: 'NONE',
            watermark: '',
            description: 'The entity, e.g. a person or organization, that created the Dataset',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 7,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              authorName: {
                name: 'authorName',
                displayName: 'Author Name',
                title: 'Name',
                type: 'TEXT',
                watermark: '1) Family Name, Given Name or 2) Organization XYZ',
                description:
                  "The name of the author, such as the person's name or the name of an organization",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: true,
                displayOrder: 8,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              authorAffiliation: {
                name: 'authorAffiliation',
                displayName: 'Author Affiliation',
                title: 'Affiliation',
                type: 'TEXT',
                watermark: 'Organization XYZ',
                description:
                  "The name of the entity affiliated with the author, e.g. an organization's name",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 9,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              authorIdentifierScheme: {
                name: 'authorIdentifierScheme',
                displayName: 'Author Identifier Type',
                title: 'Identifier Type',
                type: 'TEXT',
                watermark: '',
                description:
                  'The type of identifier that uniquely identifies the author (e.g. ORCID, ISNI)',
                multiple: false,
                isControlledVocabulary: true,
                controlledVocabularyValues: [
                  'ORCID',
                  'ISNI',
                  'LCNA',
                  'VIAF',
                  'GND',
                  'DAI',
                  'ResearcherID',
                  'ScopusID'
                ],
                displayFormat: '- #VALUE:',
                isRequired: false,
                displayOrder: 10,
                typeClass: 'controlledVocabulary',
                displayOnCreate: true
              },
              authorIdentifier: {
                name: 'authorIdentifier',
                displayName: 'Author Identifier',
                title: 'Identifier',
                type: 'TEXT',
                watermark: '',
                description: 'Uniquely identifies the author when paired with an identifier type',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 11,
                typeClass: 'primitive',
                displayOnCreate: true
              }
            }
          },
          datasetContact: {
            name: 'datasetContact',
            displayName: 'Point of Contact',
            title: 'Point of Contact',
            type: 'NONE',
            watermark: '',
            description:
              'The entity, e.g. a person or organization, that users of the Dataset can contact with questions',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 12,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              datasetContactName: {
                name: 'datasetContactName',
                displayName: 'Point of Contact Name',
                title: 'Name',
                type: 'TEXT',
                watermark: '1) FamilyName, GivenName or 2) Organization',
                description:
                  "The name of the point of contact, e.g. the person's name or the name of an organization",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 13,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              datasetContactAffiliation: {
                name: 'datasetContactAffiliation',
                displayName: 'Point of Contact Affiliation',
                title: 'Affiliation',
                type: 'TEXT',
                watermark: 'Organization XYZ',
                description:
                  "The name of the entity affiliated with the point of contact, e.g. an organization's name",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 14,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              datasetContactEmail: {
                name: 'datasetContactEmail',
                displayName: 'Point of Contact E-mail',
                title: 'E-mail',
                type: 'EMAIL',
                watermark: 'name@email.xyz',
                description: "The point of contact's email address",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#EMAIL',
                isRequired: true,
                displayOrder: 15,
                typeClass: 'primitive',
                displayOnCreate: true
              }
            }
          },
          dsDescription: {
            name: 'dsDescription',
            displayName: 'Description',
            title: 'Description',
            type: 'NONE',
            watermark: '',
            description: 'A summary describing the purpose, nature, and scope of the Dataset',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 16,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              dsDescriptionValue: {
                name: 'dsDescriptionValue',
                displayName: 'Description Text',
                title: 'Text',
                type: 'TEXTBOX',
                watermark: '',
                description: 'A summary describing the purpose, nature, and scope of the Dataset',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: true,
                displayOrder: 17,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              dsDescriptionDate: {
                name: 'dsDescriptionDate',
                displayName: 'Description Date',
                title: 'Date',
                type: 'DATE',
                watermark: 'YYYY-MM-DD',
                description:
                  'The date when the description was added to the Dataset. If the Dataset contains more than one description, e.g. the data producer supplied one description and the data repository supplied another, this date is used to distinguish between the descriptions',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 18,
                typeClass: 'primitive',
                displayOnCreate: true
              }
            }
          },
          subject: {
            name: 'subject',
            displayName: 'Subject',
            title: 'Subject',
            type: 'TEXT',
            watermark: '',
            description: 'The area of study relevant to the Dataset',
            multiple: true,
            isControlledVocabulary: true,
            controlledVocabularyValues: SUBJECT_FIELD_VOCAB_VALUES,
            displayFormat: '',
            isRequired: true,
            displayOrder: 19,
            typeClass: 'controlledVocabulary',
            displayOnCreate: true
          },
          keyword: {
            name: 'keyword',
            displayName: 'Keyword',
            title: 'Keyword',
            type: 'NONE',
            watermark: '',
            description:
              'A key term that describes an important aspect of the Dataset and information about any controlled vocabulary used',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 20,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              keywordValue: {
                name: 'keywordValue',
                displayName: 'Keyword Term',
                title: 'Term',
                type: 'TEXT',
                watermark: '',
                description: 'A key term that describes important aspects of the Dataset',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 21,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              keywordTermURI: {
                name: 'keywordTermURI',
                displayName: 'Keyword Term URI',
                title: 'Term URI',
                type: 'URL',
                watermark: 'https://',
                description: 'A URI that points to the web presence of the Keyword Term',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<a href="#VALUE" target="_blank" rel="noopener">#VALUE</a>',
                isRequired: false,
                displayOrder: 22,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              keywordVocabulary: {
                name: 'keywordVocabulary',
                displayName: 'Keyword Controlled Vocabulary Name',
                title: 'Controlled Vocabulary Name',
                type: 'TEXT',
                watermark: '',
                description:
                  'The controlled vocabulary used for the keyword term (e.g. LCSH, MeSH)',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 23,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              keywordVocabularyURI: {
                name: 'keywordVocabularyURI',
                displayName: 'Keyword Controlled Vocabulary URL',
                title: 'Controlled Vocabulary URL',
                type: 'URL',
                watermark: 'https://',
                description:
                  "The URL where one can access information about the term's controlled vocabulary",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<a href="#VALUE" target="_blank" rel="noopener">#VALUE</a>',
                isRequired: false,
                displayOrder: 24,
                typeClass: 'primitive',
                displayOnCreate: true
              }
            }
          },
          publication: {
            name: 'publication',
            displayName: 'Related Publication',
            title: 'Related Publication',
            type: 'NONE',
            watermark: '',
            description:
              'The article or report that uses the data in the Dataset. The full list of related publications will be displayed on the metadata tab',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 29,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              publicationCitation: {
                name: 'publicationCitation',
                displayName: 'Related Publication Citation',
                title: 'Citation',
                type: 'TEXTBOX',
                watermark: '',
                description: 'The full bibliographic citation for the related publication',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 30,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              publicationIDType: {
                name: 'publicationIDType',
                displayName: 'Related Publication Identifier Type',
                title: 'Identifier Type',
                type: 'TEXT',
                watermark: '',
                description:
                  'The type of identifier that uniquely identifies a related publication',
                multiple: false,
                isControlledVocabulary: true,
                controlledVocabularyValues: [
                  'ark',
                  'arXiv',
                  'bibcode',
                  'cstr',
                  'doi',
                  'ean13',
                  'eissn',
                  'handle',
                  'isbn',
                  'issn',
                  'istc',
                  'lissn',
                  'lsid',
                  'pmid',
                  'purl',
                  'upc',
                  'url',
                  'urn',
                  'DASH-NRS'
                ],
                displayFormat: '#VALUE: ',
                isRequired: false,
                displayOrder: 31,
                typeClass: 'controlledVocabulary',
                displayOnCreate: true
              },
              publicationIDNumber: {
                name: 'publicationIDNumber',
                displayName: 'Related Publication Identifier',
                title: 'Identifier',
                type: 'TEXT',
                watermark: '',
                description: 'The identifier for a related publication',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 32,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              publicationURL: {
                name: 'publicationURL',
                displayName: 'Related Publication URL',
                title: 'URL',
                type: 'URL',
                watermark: 'https://',
                description:
                  'The URL form of the identifier entered in the Identifier field, e.g. the DOI URL if a DOI was entered in the Identifier field. Used to display what was entered in the ID Type and ID Number fields as a link. If what was entered in the Identifier field has no URL form, the URL of the publication webpage is used, e.g. a journal article webpage',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<a href="#VALUE" target="_blank" rel="noopener">#VALUE</a>',
                isRequired: false,
                displayOrder: 33,
                typeClass: 'primitive',
                displayOnCreate: true
              }
            }
          },
          notesText: {
            name: 'notesText',
            displayName: 'Notes',
            title: 'Notes',
            type: 'TEXTBOX',
            watermark: '',
            description: 'Additional information about the Dataset',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 34,
            typeClass: 'primitive',
            displayOnCreate: true
          }
        }
      },
      {
        id: 2,
        name: 'geospatial',
        displayName: 'Geospatial Metadata',
        displayOnCreate: false,
        metadataFields: {
          geographicUnit: {
            name: 'geographicUnit',
            displayName: 'Geographic Unit',
            title: 'Geographic Unit',
            type: 'TEXT',
            watermark: '',
            description:
              'Lowest level of geographic aggregation covered by the Dataset, e.g., village, county, region.',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 5,
            typeClass: 'primitive',
            displayOnCreate: true
          },
          geographicCoverage: {
            name: 'geographicCoverage',
            displayName: 'Geographic Coverage',
            title: 'Geographic Coverage',
            type: 'NONE',
            watermark: '',
            description:
              'Information on the geographic coverage of the data. Includes the total geographic scope of the data.',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 0,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              country: {
                name: 'country',
                displayName: 'Geographic Coverage Country / Nation',
                title: 'Country / Nation',
                type: 'TEXT',
                watermark: '',
                description: 'The country or nation that the Dataset is about.',
                multiple: false,
                isControlledVocabulary: true,
                controlledVocabularyValues: COUNTRY_FIELD_VOCAB_VALUES,
                displayFormat: '#VALUE, ',
                isRequired: true,
                displayOrder: 1,
                typeClass: 'controlledVocabulary',
                displayOnCreate: false
              },
              state: {
                name: 'state',
                displayName: 'Geographic Coverage State / Province',
                title: 'State / Province',
                type: 'TEXT',
                watermark: '',
                description:
                  'The state or province that the Dataset is about. Use GeoNames for correct spelling and avoid abbreviations.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE, ',
                isRequired: false,
                displayOrder: 2,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              city: {
                name: 'city',
                displayName: 'Geographic Coverage City',
                title: 'City',
                type: 'TEXT',
                watermark: '',
                description:
                  'The name of the city that the Dataset is about. Use GeoNames for correct spelling and avoid abbreviations.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE, ',
                isRequired: false,
                displayOrder: 3,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              otherGeographicCoverage: {
                name: 'otherGeographicCoverage',
                displayName: 'Geographic Coverage Other',
                title: 'Other',
                type: 'TEXT',
                watermark: '',
                description: 'Other information on the geographic coverage of the data.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE, ',
                isRequired: false,
                displayOrder: 4,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          }
        }
      },
      ...(block ? [block] : [])
    ]
  }

  static getByCollectionIdDisplayedOnCreateFalse(): MetadataBlockInfo[] {
    return [
      {
        id: 1,
        name: 'citation',
        displayName: 'Citation Metadata',
        displayOnCreate: true,
        metadataFields: {
          title: {
            name: 'title',
            displayName: 'Title',
            title: 'Title',
            type: 'TEXT',
            watermark: '',
            description: 'The main title of the Dataset',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 0,
            typeClass: 'primitive',
            displayOnCreate: true
          },
          subtitle: {
            name: 'subtitle',
            displayName: 'Subtitle',
            title: 'Subtitle',
            type: 'TEXT',
            watermark: '',
            description:
              'A secondary title that amplifies or states certain limitations on the main title',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 1,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          alternativeTitle: {
            name: 'alternativeTitle',
            displayName: 'Alternative Title',
            title: 'Alternative Title',
            type: 'TEXT',
            watermark: '',
            description:
              'Either 1) a title commonly used to refer to the Dataset or 2) an abbreviation of the main title',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 2,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          alternativeURL: {
            name: 'alternativeURL',
            displayName: 'Alternative URL',
            title: 'Alternative URL',
            type: 'URL',
            watermark: 'https://',
            description:
              'Another URL where one can view or access the data in the Dataset, e.g. a project or personal webpage',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '<a href="#VALUE" target="_blank">#VALUE</a>',
            isRequired: false,
            displayOrder: 3,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          otherId: {
            name: 'otherId',
            displayName: 'Other Identifier',
            title: 'Other Identifier',
            type: 'NONE',
            watermark: '',
            description:
              "Another unique identifier for the Dataset (e.g. producer's or another repository's identifier)",
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: ':',
            isRequired: false,
            displayOrder: 4,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              otherIdAgency: {
                name: 'otherIdAgency',
                displayName: 'Other Identifier Agency',
                title: 'Agency',
                type: 'TEXT',
                watermark: '',
                description: 'The name of the agency that generated the other identifier',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 5,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              otherIdValue: {
                name: 'otherIdValue',
                displayName: 'Other Identifier Identifier',
                title: 'Identifier',
                type: 'TEXT',
                watermark: '',
                description: 'Another identifier uniquely identifies the Dataset',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 6,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          author: {
            name: 'author',
            displayName: 'Author',
            title: 'Author',
            type: 'NONE',
            watermark: '',
            description: 'The entity, e.g. a person or organization, that created the Dataset',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 7,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              authorName: {
                name: 'authorName',
                displayName: 'Author Name',
                title: 'Name',
                type: 'TEXT',
                watermark: '1) Family Name, Given Name or 2) Organization XYZ',
                description:
                  "The name of the author, such as the person's name or the name of an organization",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: true,
                displayOrder: 8,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              authorAffiliation: {
                name: 'authorAffiliation',
                displayName: 'Author Affiliation',
                title: 'Affiliation',
                type: 'TEXT',
                watermark: 'Organization XYZ',
                description:
                  "The name of the entity affiliated with the author, e.g. an organization's name",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 9,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              authorIdentifierScheme: {
                name: 'authorIdentifierScheme',
                displayName: 'Author Identifier Type',
                title: 'Identifier Type',
                type: 'TEXT',
                watermark: '',
                description:
                  'The type of identifier that uniquely identifies the author (e.g. ORCID, ISNI)',
                multiple: false,
                isControlledVocabulary: true,
                controlledVocabularyValues: [
                  'ORCID',
                  'ISNI',
                  'LCNA',
                  'VIAF',
                  'GND',
                  'DAI',
                  'ResearcherID',
                  'ScopusID'
                ],
                displayFormat: '- #VALUE:',
                isRequired: false,
                displayOrder: 10,
                typeClass: 'controlledVocabulary',
                displayOnCreate: true
              },
              authorIdentifier: {
                name: 'authorIdentifier',
                displayName: 'Author Identifier',
                title: 'Identifier',
                type: 'TEXT',
                watermark: '',
                description: 'Uniquely identifies the author when paired with an identifier type',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 11,
                typeClass: 'primitive',
                displayOnCreate: true
              }
            }
          },
          datasetContact: {
            name: 'datasetContact',
            displayName: 'Point of Contact',
            title: 'Point of Contact',
            type: 'NONE',
            watermark: '',
            description:
              'The entity, e.g. a person or organization, that users of the Dataset can contact with questions',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 12,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              datasetContactName: {
                name: 'datasetContactName',
                displayName: 'Point of Contact Name',
                title: 'Name',
                type: 'TEXT',
                watermark: '1) FamilyName, GivenName or 2) Organization',
                description:
                  "The name of the point of contact, e.g. the person's name or the name of an organization",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 13,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              datasetContactAffiliation: {
                name: 'datasetContactAffiliation',
                displayName: 'Point of Contact Affiliation',
                title: 'Affiliation',
                type: 'TEXT',
                watermark: 'Organization XYZ',
                description:
                  "The name of the entity affiliated with the point of contact, e.g. an organization's name",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 14,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              datasetContactEmail: {
                name: 'datasetContactEmail',
                displayName: 'Point of Contact E-mail',
                title: 'E-mail',
                type: 'EMAIL',
                watermark: 'name@email.xyz',
                description: "The point of contact's email address",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#EMAIL',
                isRequired: true,
                displayOrder: 15,
                typeClass: 'primitive',
                displayOnCreate: true
              }
            }
          },
          dsDescription: {
            name: 'dsDescription',
            displayName: 'Description',
            title: 'Description',
            type: 'NONE',
            watermark: '',
            description: 'A summary describing the purpose, nature, and scope of the Dataset',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 16,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              dsDescriptionValue: {
                name: 'dsDescriptionValue',
                displayName: 'Description Text',
                title: 'Text',
                type: 'TEXTBOX',
                watermark: '',
                description: 'A summary describing the purpose, nature, and scope of the Dataset',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: true,
                displayOrder: 17,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              dsDescriptionDate: {
                name: 'dsDescriptionDate',
                displayName: 'Description Date',
                title: 'Date',
                type: 'DATE',
                watermark: 'YYYY-MM-DD',
                description:
                  'The date when the description was added to the Dataset. If the Dataset contains more than one description, e.g. the data producer supplied one description and the data repository supplied another, this date is used to distinguish between the descriptions',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 18,
                typeClass: 'primitive',
                displayOnCreate: true
              }
            }
          },
          subject: {
            name: 'subject',
            displayName: 'Subject',
            title: 'Subject',
            type: 'TEXT',
            watermark: '',
            description: 'The area of study relevant to the Dataset',
            multiple: true,
            isControlledVocabulary: true,
            controlledVocabularyValues: SUBJECT_FIELD_VOCAB_VALUES,
            displayFormat: '',
            isRequired: true,
            displayOrder: 19,
            typeClass: 'controlledVocabulary',
            displayOnCreate: true
          },
          keyword: {
            name: 'keyword',
            displayName: 'Keyword',
            title: 'Keyword',
            type: 'NONE',
            watermark: '',
            description:
              'A key term that describes an important aspect of the Dataset and information about any controlled vocabulary used',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 20,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              keywordValue: {
                name: 'keywordValue',
                displayName: 'Keyword Term',
                title: 'Term',
                type: 'TEXT',
                watermark: '',
                description: 'A key term that describes important aspects of the Dataset',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 21,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              keywordTermURI: {
                name: 'keywordTermURI',
                displayName: 'Keyword Term URI',
                title: 'Term URI',
                type: 'URL',
                watermark: 'https://',
                description: 'A URI that points to the web presence of the Keyword Term',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<a href="#VALUE" target="_blank" rel="noopener">#VALUE</a>',
                isRequired: false,
                displayOrder: 22,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              keywordVocabulary: {
                name: 'keywordVocabulary',
                displayName: 'Keyword Controlled Vocabulary Name',
                title: 'Controlled Vocabulary Name',
                type: 'TEXT',
                watermark: '',
                description:
                  'The controlled vocabulary used for the keyword term (e.g. LCSH, MeSH)',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 23,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              keywordVocabularyURI: {
                name: 'keywordVocabularyURI',
                displayName: 'Keyword Controlled Vocabulary URL',
                title: 'Controlled Vocabulary URL',
                type: 'URL',
                watermark: 'https://',
                description:
                  "The URL where one can access information about the term's controlled vocabulary",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<a href="#VALUE" target="_blank" rel="noopener">#VALUE</a>',
                isRequired: false,
                displayOrder: 24,
                typeClass: 'primitive',
                displayOnCreate: true
              }
            }
          },
          topicClassification: {
            name: 'topicClassification',
            displayName: 'Topic Classification',
            title: 'Topic Classification',
            type: 'NONE',
            watermark: '',
            description:
              'Indicates a broad, important topic or subject that the Dataset covers and information about any controlled vocabulary used',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 25,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              topicClassValue: {
                name: 'topicClassValue',
                displayName: 'Topic Classification Term',
                title: 'Term',
                type: 'TEXT',
                watermark: '',
                description: 'A topic or subject term',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 26,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              topicClassVocab: {
                name: 'topicClassVocab',
                displayName: 'Topic Classification Controlled Vocabulary Name',
                title: 'Controlled Vocabulary Name',
                type: 'TEXT',
                watermark: '',
                description:
                  'The controlled vocabulary used for the keyword term (e.g. LCSH, MeSH)',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 27,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              topicClassVocabURI: {
                name: 'topicClassVocabURI',
                displayName: 'Topic Classification Controlled Vocabulary URL',
                title: 'Controlled Vocabulary URL',
                type: 'URL',
                watermark: 'https://',
                description:
                  "The URL where one can access information about the term's controlled vocabulary",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<a href="#VALUE" target="_blank" rel="noopener">#VALUE</a>',
                isRequired: false,
                displayOrder: 28,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          publication: {
            name: 'publication',
            displayName: 'Related Publication',
            title: 'Related Publication',
            type: 'NONE',
            watermark: '',
            description:
              'The article or report that uses the data in the Dataset. The full list of related publications will be displayed on the metadata tab',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 29,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              publicationCitation: {
                name: 'publicationCitation',
                displayName: 'Related Publication Citation',
                title: 'Citation',
                type: 'TEXTBOX',
                watermark: '',
                description: 'The full bibliographic citation for the related publication',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 30,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              publicationIDType: {
                name: 'publicationIDType',
                displayName: 'Related Publication Identifier Type',
                title: 'Identifier Type',
                type: 'TEXT',
                watermark: '',
                description:
                  'The type of identifier that uniquely identifies a related publication',
                multiple: false,
                isControlledVocabulary: true,
                controlledVocabularyValues: [
                  'ark',
                  'arXiv',
                  'bibcode',
                  'cstr',
                  'doi',
                  'ean13',
                  'eissn',
                  'handle',
                  'isbn',
                  'issn',
                  'istc',
                  'lissn',
                  'lsid',
                  'pmid',
                  'purl',
                  'upc',
                  'url',
                  'urn',
                  'DASH-NRS'
                ],
                displayFormat: '#VALUE: ',
                isRequired: false,
                displayOrder: 31,
                typeClass: 'controlledVocabulary',
                displayOnCreate: true
              },
              publicationIDNumber: {
                name: 'publicationIDNumber',
                displayName: 'Related Publication Identifier',
                title: 'Identifier',
                type: 'TEXT',
                watermark: '',
                description: 'The identifier for a related publication',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 32,
                typeClass: 'primitive',
                displayOnCreate: true
              },
              publicationURL: {
                name: 'publicationURL',
                displayName: 'Related Publication URL',
                title: 'URL',
                type: 'URL',
                watermark: 'https://',
                description:
                  'The URL form of the identifier entered in the Identifier field, e.g. the DOI URL if a DOI was entered in the Identifier field. Used to display what was entered in the ID Type and ID Number fields as a link. If what was entered in the Identifier field has no URL form, the URL of the publication webpage is used, e.g. a journal article webpage',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<a href="#VALUE" target="_blank" rel="noopener">#VALUE</a>',
                isRequired: false,
                displayOrder: 33,
                typeClass: 'primitive',
                displayOnCreate: true
              }
            }
          },
          notesText: {
            name: 'notesText',
            displayName: 'Notes',
            title: 'Notes',
            type: 'TEXTBOX',
            watermark: '',
            description: 'Additional information about the Dataset',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 34,
            typeClass: 'primitive',
            displayOnCreate: true
          },
          language: {
            name: 'language',
            displayName: 'Language',
            title: 'Language',
            type: 'TEXT',
            watermark: '',
            description: "A language that the Dataset's files is written in",
            multiple: true,
            isControlledVocabulary: true,
            controlledVocabularyValues: [
              'Abkhaz',
              'Afar',
              'Afrikaans',
              'Akan',
              'Albanian',
              'Amharic',
              'Arabic',
              'Aragonese',
              'Armenian',
              'Assamese',
              'Avaric',
              'Avestan',
              'Aymara',
              'Azerbaijani',
              'Bambara',
              'Bashkir',
              'Basque',
              'Belarusian',
              'Bengali, Bangla',
              'Bihari',
              'Bislama',
              'Bosnian',
              'Breton',
              'Bulgarian',
              'Burmese',
              'Catalan,Valencian',
              'Chamorro',
              'Chechen',
              'Chichewa, Chewa, Nyanja',
              'Chinese',
              'Chuvash',
              'Cornish',
              'Corsican',
              'Cree',
              'Croatian',
              'Czech',
              'Danish',
              'Divehi, Dhivehi, Maldivian',
              'Dutch',
              'Dzongkha',
              'English',
              'Esperanto',
              'Estonian',
              'Ewe',
              'Faroese',
              'Fijian',
              'Finnish',
              'French',
              'Fula, Fulah, Pulaar, Pular',
              'Galician',
              'Georgian',
              'German',
              'Greek (modern)',
              'Guaraní',
              'Gujarati',
              'Haitian, Haitian Creole',
              'Hausa',
              'Hebrew (modern)',
              'Herero',
              'Hindi',
              'Hiri Motu',
              'Hungarian',
              'Interlingua',
              'Indonesian',
              'Interlingue',
              'Irish',
              'Igbo',
              'Inupiaq',
              'Ido',
              'Icelandic',
              'Italian',
              'Inuktitut',
              'Japanese',
              'Javanese',
              'Kalaallisut, Greenlandic',
              'Kannada',
              'Kanuri',
              'Kashmiri',
              'Kazakh',
              'Khmer',
              'Kikuyu, Gikuyu',
              'Kinyarwanda',
              'Kyrgyz',
              'Komi',
              'Kongo',
              'Korean',
              'Kurdish',
              'Kwanyama, Kuanyama',
              'Latin',
              'Luxembourgish, Letzeburgesch',
              'Ganda',
              'Limburgish, Limburgan, Limburger',
              'Lingala',
              'Lao',
              'Lithuanian',
              'Luba-Katanga',
              'Latvian',
              'Manx',
              'Macedonian',
              'Malagasy',
              'Malay',
              'Malayalam',
              'Maltese',
              'Māori',
              'Marathi (Marāṭhī)',
              'Marshallese',
              'Mixtepec Mixtec',
              'Mongolian',
              'Nauru',
              'Navajo, Navaho',
              'Northern Ndebele',
              'Nepali',
              'Ndonga',
              'Norwegian Bokmål',
              'Norwegian Nynorsk',
              'Norwegian',
              'Nuosu',
              'Southern Ndebele',
              'Occitan',
              'Ojibwe, Ojibwa',
              'Old Church Slavonic,Church Slavonic,Old Bulgarian',
              'Oromo',
              'Oriya',
              'Ossetian, Ossetic',
              'Panjabi, Punjabi',
              'Pāli',
              'Persian (Farsi)',
              'Polish',
              'Pashto, Pushto',
              'Portuguese',
              'Quechua',
              'Romansh',
              'Kirundi',
              'Romanian',
              'Russian',
              'Sanskrit (Saṁskṛta)',
              'Sardinian',
              'Sindhi',
              'Northern Sami',
              'Samoan',
              'Sango',
              'Serbian',
              'Scottish Gaelic, Gaelic',
              'Shona',
              'Sinhala, Sinhalese',
              'Slovak',
              'Slovene',
              'Somali',
              'Southern Sotho',
              'Spanish, Castilian',
              'Sundanese',
              'Swahili',
              'Swati',
              'Swedish',
              'Tamil',
              'Telugu',
              'Tajik',
              'Thai',
              'Tigrinya',
              'Tibetan Standard, Tibetan, Central',
              'Turkmen',
              'Tagalog',
              'Tswana',
              'Tonga (Tonga Islands)',
              'Turkish',
              'Tsonga',
              'Tatar',
              'Twi',
              'Tahitian',
              'Uyghur, Uighur',
              'Ukrainian',
              'Urdu',
              'Uzbek',
              'Venda',
              'Vietnamese',
              'Volapük',
              'Walloon',
              'Welsh',
              'Wolof',
              'Western Frisian',
              'Xhosa',
              'Yiddish',
              'Yoruba',
              'Zhuang, Chuang',
              'Zulu',
              'Not applicable'
            ],
            displayFormat: '',
            isRequired: false,
            displayOrder: 35,
            typeClass: 'controlledVocabulary',
            displayOnCreate: false
          },
          producer: {
            name: 'producer',
            displayName: 'Producer',
            title: 'Producer',
            type: 'NONE',
            watermark: '',
            description:
              'The entity, such a person or organization, managing the finances or other administrative processes involved in the creation of the Dataset',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 36,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              producerName: {
                name: 'producerName',
                displayName: 'Producer Name',
                title: 'Name',
                type: 'TEXT',
                watermark: '1) FamilyName, GivenName or 2) Organization',
                description:
                  "The name of the entity, e.g. the person's name or the name of an organization",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: true,
                displayOrder: 37,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              producerAffiliation: {
                name: 'producerAffiliation',
                displayName: 'Producer Affiliation',
                title: 'Affiliation',
                type: 'TEXT',
                watermark: 'Organization XYZ',
                description:
                  "The name of the entity affiliated with the producer, e.g. an organization's name",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 38,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              producerAbbreviation: {
                name: 'producerAbbreviation',
                displayName: 'Producer Abbreviated Name',
                title: 'Abbreviated Name',
                type: 'TEXT',
                watermark: '',
                description: "The producer's abbreviated name (e.g. IQSS, ICPSR)",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 39,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              producerURL: {
                name: 'producerURL',
                displayName: 'Producer URL',
                title: 'URL',
                type: 'URL',
                watermark: 'https://',
                description: "The URL of the producer's website",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<a href="#VALUE" target="_blank" rel="noopener">#VALUE</a>',
                isRequired: false,
                displayOrder: 40,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              producerLogoURL: {
                name: 'producerLogoURL',
                displayName: 'Producer Logo URL',
                title: 'Logo URL',
                type: 'URL',
                watermark: 'https://',
                description: "The URL of the producer's logo",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<img src="#VALUE" alt="#NAME" class="metadata-logo"/><br/>',
                isRequired: false,
                displayOrder: 41,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          productionDate: {
            name: 'productionDate',
            displayName: 'Production Date',
            title: 'Production Date',
            type: 'DATE',
            watermark: 'YYYY-MM-DD',
            description:
              'The date when the data were produced (not distributed, published, or archived)',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 42,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          productionPlace: {
            name: 'productionPlace',
            displayName: 'Production Location',
            title: 'Production Location',
            type: 'TEXT',
            watermark: '',
            description:
              'The location where the data and any related materials were produced or collected',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 43,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          contributor: {
            name: 'contributor',
            displayName: 'Contributor',
            title: 'Contributor',
            type: 'NONE',
            watermark: '',
            description:
              'The entity, such as a person or organization, responsible for collecting, managing, or otherwise contributing to the development of the Dataset',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: ':',
            isRequired: false,
            displayOrder: 44,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              contributorType: {
                name: 'contributorType',
                displayName: 'Contributor Type',
                title: 'Type',
                type: 'TEXT',
                watermark: '',
                description: 'Indicates the type of contribution made to the dataset',
                multiple: false,
                isControlledVocabulary: true,
                controlledVocabularyValues: [
                  'Data Collector',
                  'Data Curator',
                  'Data Manager',
                  'Editor',
                  'Funder',
                  'Hosting Institution',
                  'Project Leader',
                  'Project Manager',
                  'Project Member',
                  'Related Person',
                  'Researcher',
                  'Research Group',
                  'Rights Holder',
                  'Sponsor',
                  'Supervisor',
                  'Work Package Leader',
                  'Other'
                ],
                displayFormat: '#VALUE ',
                isRequired: false,
                displayOrder: 45,
                typeClass: 'controlledVocabulary',
                displayOnCreate: false
              },
              contributorName: {
                name: 'contributorName',
                displayName: 'Contributor Name',
                title: 'Name',
                type: 'TEXT',
                watermark: '1) FamilyName, GivenName or 2) Organization',
                description:
                  "The name of the contributor, e.g. the person's name or the name of an organization",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 46,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          grantNumber: {
            name: 'grantNumber',
            displayName: 'Funding Information',
            title: 'Funding Information',
            type: 'NONE',
            watermark: '',
            description: "Information about the Dataset's financial support",
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: ':',
            isRequired: false,
            displayOrder: 47,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              grantNumberAgency: {
                name: 'grantNumberAgency',
                displayName: 'Funding Information Agency',
                title: 'Agency',
                type: 'TEXT',
                watermark: 'Organization XYZ',
                description: 'The agency that provided financial support for the Dataset',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 48,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              grantNumberValue: {
                name: 'grantNumberValue',
                displayName: 'Funding Information Identifier',
                title: 'Identifier',
                type: 'TEXT',
                watermark: '',
                description:
                  'The grant identifier or contract identifier of the agency that provided financial support for the Dataset',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 49,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          distributor: {
            name: 'distributor',
            displayName: 'Distributor',
            title: 'Distributor',
            type: 'NONE',
            watermark: '',
            description:
              'The entity, such as a person or organization, designated to generate copies of the Dataset, including any editions or revisions',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 50,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              distributorName: {
                name: 'distributorName',
                displayName: 'Distributor Name',
                title: 'Name',
                type: 'TEXT',
                watermark: '1) FamilyName, GivenName or 2) Organization',
                description:
                  "The name of the entity, e.g. the person's name or the name of an organization",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 51,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              distributorAffiliation: {
                name: 'distributorAffiliation',
                displayName: 'Distributor Affiliation',
                title: 'Affiliation',
                type: 'TEXT',
                watermark: 'Organization XYZ',
                description:
                  "The name of the entity affiliated with the distributor, e.g. an organization's name",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 52,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              distributorAbbreviation: {
                name: 'distributorAbbreviation',
                displayName: 'Distributor Abbreviated Name',
                title: 'Abbreviated Name',
                type: 'TEXT',
                watermark: '',
                description: "The distributor's abbreviated name (e.g. IQSS, ICPSR)",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '(#VALUE)',
                isRequired: false,
                displayOrder: 53,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              distributorURL: {
                name: 'distributorURL',
                displayName: 'Distributor URL',
                title: 'URL',
                type: 'URL',
                watermark: 'https://',
                description: "The URL of the distributor's webpage",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<a href="#VALUE" target="_blank" rel="noopener">#VALUE</a>',
                isRequired: false,
                displayOrder: 54,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              distributorLogoURL: {
                name: 'distributorLogoURL',
                displayName: 'Distributor Logo URL',
                title: 'Logo URL',
                type: 'URL',
                watermark: 'https://',
                description:
                  "The URL of the distributor's logo image, used to show the image on the Dataset's page",
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '<img src="#VALUE" alt="#NAME" class="metadata-logo"/><br/>',
                isRequired: false,
                displayOrder: 55,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          distributionDate: {
            name: 'distributionDate',
            displayName: 'Distribution Date',
            title: 'Distribution Date',
            type: 'DATE',
            watermark: 'YYYY-MM-DD',
            description:
              'The date when the Dataset was made available for distribution/presentation',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 56,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          depositor: {
            name: 'depositor',
            displayName: 'Depositor',
            title: 'Depositor',
            type: 'TEXT',
            watermark: '1) FamilyName, GivenName or 2) Organization',
            description:
              'The entity, such as a person or organization, that deposited the Dataset in the repository',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 57,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          dateOfDeposit: {
            name: 'dateOfDeposit',
            displayName: 'Deposit Date',
            title: 'Deposit Date',
            type: 'DATE',
            watermark: 'YYYY-MM-DD',
            description: 'The date when the Dataset was deposited into the repository',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 58,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          timePeriodCovered: {
            name: 'timePeriodCovered',
            displayName: 'Time Period',
            title: 'Time Period',
            type: 'NONE',
            watermark: '',
            description:
              'The time period that the data refer to. Also known as span. This is the time period covered by the data, not the dates of coding, collecting data, or making documents machine-readable',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: ';',
            isRequired: false,
            displayOrder: 59,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              timePeriodCoveredStart: {
                name: 'timePeriodCoveredStart',
                displayName: 'Time Period Start Date',
                title: 'Start Date',
                type: 'DATE',
                watermark: 'YYYY-MM-DD',
                description: 'The start date of the time period that the data refer to',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#NAME: #VALUE ',
                isRequired: false,
                displayOrder: 60,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              timePeriodCoveredEnd: {
                name: 'timePeriodCoveredEnd',
                displayName: 'Time Period End Date',
                title: 'End Date',
                type: 'DATE',
                watermark: 'YYYY-MM-DD',
                description: 'The end date of the time period that the data refer to',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#NAME: #VALUE ',
                isRequired: false,
                displayOrder: 61,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          dateOfCollection: {
            name: 'dateOfCollection',
            displayName: 'Date of Collection',
            title: 'Date of Collection',
            type: 'NONE',
            watermark: '',
            description: 'The dates when the data were collected or generated',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: ';',
            isRequired: false,
            displayOrder: 62,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              dateOfCollectionStart: {
                name: 'dateOfCollectionStart',
                displayName: 'Date of Collection Start Date',
                title: 'Start Date',
                type: 'DATE',
                watermark: 'YYYY-MM-DD',
                description: 'The date when the data collection started',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#NAME: #VALUE ',
                isRequired: false,
                displayOrder: 63,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              dateOfCollectionEnd: {
                name: 'dateOfCollectionEnd',
                displayName: 'Date of Collection End Date',
                title: 'End Date',
                type: 'DATE',
                watermark: 'YYYY-MM-DD',
                description: 'The date when the data collection ended',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#NAME: #VALUE ',
                isRequired: false,
                displayOrder: 64,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          kindOfData: {
            name: 'kindOfData',
            displayName: 'Data Type',
            title: 'Data Type',
            type: 'TEXT',
            watermark: '',
            description:
              'The type of data included in the files (e.g. survey data, clinical data, or machine-readable text)',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 65,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          series: {
            name: 'series',
            displayName: 'Series',
            title: 'Series',
            type: 'NONE',
            watermark: '',
            description: 'Information about the dataset series to which the Dataset belong',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: ':',
            isRequired: false,
            displayOrder: 66,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              seriesName: {
                name: 'seriesName',
                displayName: 'Series Name',
                title: 'Name',
                type: 'TEXT',
                watermark: '',
                description: 'The name of the dataset series',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 67,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              seriesInformation: {
                name: 'seriesInformation',
                displayName: 'Series Information',
                title: 'Information',
                type: 'TEXTBOX',
                watermark: '',
                description:
                  'Can include 1) a history of the series and 2) a summary of features that apply to the series',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 68,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          software: {
            name: 'software',
            displayName: 'Software',
            title: 'Software',
            type: 'NONE',
            watermark: '',
            description: 'Information about the software used to generate the Dataset',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: ',',
            isRequired: false,
            displayOrder: 69,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              softwareName: {
                name: 'softwareName',
                displayName: 'Software Name',
                title: 'Name',
                type: 'TEXT',
                watermark: '',
                description: 'The name of software used to generate the Dataset',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE',
                isRequired: false,
                displayOrder: 70,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              softwareVersion: {
                name: 'softwareVersion',
                displayName: 'Software Version',
                title: 'Version',
                type: 'TEXT',
                watermark: '',
                description: 'The version of the software used to generate the Dataset, e.g. 4.11',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#NAME: #VALUE',
                isRequired: false,
                displayOrder: 71,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          relatedMaterial: {
            name: 'relatedMaterial',
            displayName: 'Related Material',
            title: 'Related Material',
            type: 'TEXTBOX',
            watermark: '',
            description:
              'Information, such as a persistent ID or citation, about the material related to the Dataset, such as appendices or sampling information available outside of the Dataset',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 72,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          relatedDatasets: {
            name: 'relatedDatasets',
            displayName: 'Related Dataset',
            title: 'Related Dataset',
            type: 'TEXTBOX',
            watermark: '',
            description:
              "Information, such as a persistent ID or citation, about a related dataset, such as previous research on the Dataset's subject",
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 73,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          otherReferences: {
            name: 'otherReferences',
            displayName: 'Other Reference',
            title: 'Other Reference',
            type: 'TEXT',
            watermark: '',
            description:
              'Information, such as a persistent ID or citation, about another type of resource that provides background or supporting material to the Dataset',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 74,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          dataSources: {
            name: 'dataSources',
            displayName: 'Data Source',
            title: 'Data Source',
            type: 'TEXTBOX',
            watermark: '',
            description:
              'Information, such as a persistent ID or citation, about sources of the Dataset (e.g. a book, article, serial, or machine-readable data file)',
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 75,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          originOfSources: {
            name: 'originOfSources',
            displayName: 'Origin of Historical Sources',
            title: 'Origin of Historical Sources',
            type: 'TEXTBOX',
            watermark: '',
            description:
              'For historical sources, the origin and any rules followed in establishing them as sources',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 76,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          characteristicOfSources: {
            name: 'characteristicOfSources',
            displayName: 'Characteristic of Sources',
            title: 'Characteristic of Sources',
            type: 'TEXTBOX',
            watermark: '',
            description: 'Characteristics not already noted elsewhere',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 77,
            typeClass: 'primitive',
            displayOnCreate: false
          },
          accessToSources: {
            name: 'accessToSources',
            displayName: 'Documentation and Access to Sources',
            title: 'Documentation and Access to Sources',
            type: 'TEXTBOX',
            watermark: '',
            description:
              '1) Methods or procedures for accessing data sources and 2) any special permissions needed for access',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 78,
            typeClass: 'primitive',
            displayOnCreate: false
          }
        }
      },
      {
        id: 2,
        name: 'geospatial',
        displayName: 'Geospatial Metadata',
        displayOnCreate: false,
        metadataFields: {
          geographicUnit: {
            name: 'geographicUnit',
            displayName: 'Geographic Unit',
            title: 'Geographic Unit',
            type: 'TEXT',
            watermark: '',
            description:
              'Lowest level of geographic aggregation covered by the Dataset, e.g., village, county, region.',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 5,
            typeClass: 'primitive',
            displayOnCreate: true
          },
          geographicCoverage: {
            name: 'geographicCoverage',
            displayName: 'Geographic Coverage',
            title: 'Geographic Coverage',
            type: 'NONE',
            watermark: '',
            description:
              'Information on the geographic coverage of the data. Includes the total geographic scope of the data.',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: true,
            displayOrder: 0,
            typeClass: 'compound',
            displayOnCreate: true,
            childMetadataFields: {
              country: {
                name: 'country',
                displayName: 'Geographic Coverage Country / Nation',
                title: 'Country / Nation',
                type: 'TEXT',
                watermark: '',
                description: 'The country or nation that the Dataset is about.',
                multiple: false,
                isControlledVocabulary: true,
                controlledVocabularyValues: COUNTRY_FIELD_VOCAB_VALUES,
                displayFormat: '#VALUE, ',
                isRequired: true,
                displayOrder: 1,
                typeClass: 'controlledVocabulary',
                displayOnCreate: false
              },
              state: {
                name: 'state',
                displayName: 'Geographic Coverage State / Province',
                title: 'State / Province',
                type: 'TEXT',
                watermark: '',
                description:
                  'The state or province that the Dataset is about. Use GeoNames for correct spelling and avoid abbreviations.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE, ',
                isRequired: false,
                displayOrder: 2,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              city: {
                name: 'city',
                displayName: 'Geographic Coverage City',
                title: 'City',
                type: 'TEXT',
                watermark: '',
                description:
                  'The name of the city that the Dataset is about. Use GeoNames for correct spelling and avoid abbreviations.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE, ',
                isRequired: false,
                displayOrder: 3,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              otherGeographicCoverage: {
                name: 'otherGeographicCoverage',
                displayName: 'Geographic Coverage Other',
                title: 'Other',
                type: 'TEXT',
                watermark: '',
                description: 'Other information on the geographic coverage of the data.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '#VALUE, ',
                isRequired: false,
                displayOrder: 4,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          },
          geographicBoundingBox: {
            name: 'geographicBoundingBox',
            displayName: 'Geographic Bounding Box',
            title: 'Geographic Bounding Box',
            type: 'NONE',
            watermark: '',
            description:
              "The fundamental geometric description for any Dataset that models geography is the geographic bounding box. It describes the minimum box, defined by west and east longitudes and north and south latitudes, which includes the largest geographic extent of the  Dataset's geographic coverage. This element is used in the first pass of a coordinate-based search. Inclusion of this element in the codebook is recommended, but is required if the bound polygon box is included. ",
            multiple: true,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOrder: 6,
            typeClass: 'compound',
            displayOnCreate: false,
            childMetadataFields: {
              westLongitude: {
                name: 'westLongitude',
                displayName: 'Geographic Bounding Box Westernmost (Left) Longitude',
                title: 'Westernmost (Left) Longitude',
                type: 'TEXT',
                watermark: '',
                description:
                  'Westernmost coordinate delimiting the geographic extent of the Dataset. A valid range of values,  expressed in decimal degrees, is -180.0 <= West  Bounding Longitude Value <= 180.0.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '',
                isRequired: false,
                displayOrder: 7,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              eastLongitude: {
                name: 'eastLongitude',
                displayName: 'Geographic Bounding Box Easternmost (Right) Longitude',
                title: 'Easternmost (Right) Longitude',
                type: 'TEXT',
                watermark: '',
                description:
                  'Easternmost coordinate delimiting the geographic extent of the Dataset. A valid range of values,  expressed in decimal degrees, is -180.0 <= East Bounding Longitude Value <= 180.0.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '',
                isRequired: false,
                displayOrder: 8,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              northLatitude: {
                name: 'northLatitude',
                displayName: 'Geographic Bounding Box Northernmost (Top) Latitude',
                title: 'Northernmost (Top) Latitude',
                type: 'TEXT',
                watermark: '',
                description:
                  'Northernmost coordinate delimiting the geographic extent of the Dataset. A valid range of values,  expressed in decimal degrees, is -90.0 <= North Bounding Latitude Value <= 90.0.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '',
                isRequired: false,
                displayOrder: 9,
                typeClass: 'primitive',
                displayOnCreate: false
              },
              southLatitude: {
                name: 'southLatitude',
                displayName: 'Geographic Bounding Box Southernmost (Bottom) Latitude',
                title: 'Southernmost (Bottom) Latitude',
                type: 'TEXT',
                watermark: '',
                description:
                  'Southernmost coordinate delimiting the geographic extent of the Dataset. A valid range of values,  expressed in decimal degrees, is -90.0 <= South Bounding Latitude Value <= 90.0.',
                multiple: false,
                isControlledVocabulary: false,
                displayFormat: '',
                isRequired: false,
                displayOrder: 10,
                typeClass: 'primitive',
                displayOnCreate: false
              }
            }
          }
        }
      }
    ]
  }

  static wrongCollectionMetadataBlocksInfo(): MetadataBlockInfo[] {
    return [
      {
        id: 1,
        name: 'citation',
        displayName: 'Citation Metadata',
        displayOnCreate: true,
        metadataFields: {
          title: {
            name: 'title',
            displayName: 'Title',
            title: 'Title',
            type: 'TEXT',
            typeClass: 'primitive',
            watermark: '',
            description: 'The main title of the Dataset',
            multiple: false,
            isControlledVocabulary: false,
            displayFormat: '',
            isRequired: false,
            displayOnCreate: true,
            displayOrder: 0
          }
        }
      }
    ]
  }
}

export const SUBJECT_FIELD_VOCAB_VALUES = ['Subject1', 'Subject2', 'Subject3', 'Subject4']
export const COUNTRY_FIELD_VOCAB_VALUES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia, Plurinational State of',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo, the Democratic Republic of the',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czech Republic',
  "Côte d'Ivoire",
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and Mcdonald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Republic of',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea, Democratic People's Republic of",
  'Korea, Republic of',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia, the Former Yugoslav Republic of',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia, Federated States of',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine, State of',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan, Province of China',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela, Bolivarian Republic of',
  'Viet Nam',
  'Virgin Islands, British',
  'Virgin Islands, U.S.',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Åland Islands'
]
