export enum SettingName {
  ZIP_DOWNLOAD_LIMIT = 'ZIP_DOWNLOAD_LIMIT',
  ALLOWED_EXTERNAL_STATUSES = 'ALLOWED_EXTERNAL_STATUSES',
  HAS_PUBLIC_STORE = 'HAS_PUBLIC_STORE',
  MAX_EMBARGO_DURATION_IN_MONTHS = 'MAX_EMBARGO_DURATION_IN_MONTHS'
}

export interface Setting<T> {
  name: SettingName
  value: T
}
