export enum SettingName {
  ZIP_DOWNLOAD_LIMIT = 'ZIP_DOWNLOAD_LIMIT',
  ALLOWED_EXTERNAL_STATUSES = 'ALLOWED_EXTERNAL_STATUSES',
  HAS_PUBLIC_STORE = 'HAS_PUBLIC_STORE',
  MAX_EMBARGO_DURATION_IN_MONTHS = 'MAX_EMBARGO_DURATION_IN_MONTHS',
  PUBLISH_DATASET_DISCLAIMER_TEXT = 'PUBLISH_DATASET_DISCLAIMER_TEXT',
  DATASET_PUBLISH_POPUP_CUSTOM_TEXT = 'DATASET_PUBLISH_POPUP_CUSTOM_TEXT'
}

export interface Setting<T> {
  name: SettingName
  value: T
}
