services:
  dev_dataverse:
    environment:
      DATAVERSE_SITEURL: http://localhost:8000
      DATAVERSE_FEATURE_API_SESSION_AUTH: 1
      DATAVERSE_FEATURE_REACT_TREE_VIEW: 1
      DATAVERSE_FEATURE_REACT_UPLOADER: 1
      DATAVERSE_REUSABLE_COMPONENTS_BASE_URL: /reusable-components

  dev_nginx:
    volumes:
      - ./reusable-components/nginx.conf:/etc/nginx/nginx.conf
      - ../dist-reusable-components/reusable-components:/usr/share/nginx/html/reusable-components:ro
