db-kind-user-store=postgres
db-url-full-user-store=jdbc:postgresql://${DATAVERSE_DB_HOST}:${DATAVERSE_DB_PORT}/dataverse
db-username-user-store=${DATAVERSE_DB_USER}
db-password-user-store=${DATAVERSE_DB_PASSWORD}
db-driver-user-store=org.postgresql.Driver
transaction-xa-enabled-user-store=false
