export const MetadataBlockInfoCitationExample = {
  name: 'citation',
  fields: {
    title: { displayFormat: '' },
    subtitle: { displayFormat: '' },
    alternativeTitle: { displayFormat: '' },
    alternativeURL: { displayFormat: '[#VALUE](#VALUE)' },
    otherId: { displayFormat: ':' },
    otherIdAgency: { displayFormat: '#VALUE' },
    otherIdValue: { displayFormat: '#VALUE' },
    author: { displayFormat: '' },
    authorName: { displayFormat: '#VALUE' },
    authorAffiliation: { displayFormat: '(#VALUE)' },
    authorIdentifierScheme: { displayFormat: '- #VALUE:' },
    authorIdentifier: { displayFormat: '#VALUE' },
    datasetContact: { displayFormat: '' },
    datasetContactName: { displayFormat: '#VALUE' },
    datasetContactAffiliation: { displayFormat: '(#VALUE)' },
    datasetContactEmail: { displayFormat: '[#VALUE](mailto:#VALUE)' },
    dsDescription: { displayFormat: '' },
    dsDescriptionValue: { displayFormat: '#VALUE' },
    dsDescriptionDate: { displayFormat: '(#VALUE)' },
    subject: { displayFormat: '' },
    keyword: { displayFormat: '' },
    keywordValue: { displayFormat: '#VALUE' },
    keywordVocabulary: { displayFormat: '(#VALUE)' },
    keywordVocabularyURI: { displayFormat: '[#VALUE](#VALUE)' },
    keywordTermURI: { displayFormat: '[#VALUE](#VALUE)' },
    topicClassification: { displayFormat: '' },
    topicClassValue: { displayFormat: '#VALUE' },
    topicClassVocab: { displayFormat: '(#VALUE)' },
    topicClassVocabURI: { displayFormat: '[#VALUE](#VALUE)' },
    publication: { displayFormat: '' },
    publicationCitation: { displayFormat: '#VALUE' },
    publicationIDType: { displayFormat: '#VALUE: ' },
    publicationIDNumber: { displayFormat: '#VALUE' },
    publicationURL: { displayFormat: '[#VALUE](#VALUE)' },
    notesText: { displayFormat: '' },
    language: { displayFormat: '' },
    producer: { displayFormat: '' },
    producerName: { displayFormat: '#VALUE' },
    producerAffiliation: { displayFormat: '(#VALUE)' },
    producerAbbreviation: { displayFormat: '(#VALUE)' },
    producerURL: { displayFormat: '[#VALUE](#VALUE)' },
    producerLogoURL: { displayFormat: '![#NAME](#VALUE)' },
    productionDate: { displayFormat: '' },
    productionPlace: { displayFormat: '' },
    contributor: { displayFormat: ':' },
    contributorType: { displayFormat: '#VALUE ' },
    contributorName: { displayFormat: '#VALUE' },
    grantNumber: { displayFormat: ':' },
    grantNumberAgency: { displayFormat: '#VALUE' },
    grantNumberValue: { displayFormat: '#VALUE' },
    distributor: { displayFormat: '' },
    distributorName: { displayFormat: '#VALUE' },
    distributorAffiliation: { displayFormat: '(#VALUE)' },
    distributorAbbreviation: { displayFormat: '(#VALUE)' },
    distributorURL: { displayFormat: '[#VALUE](#VALUE)' },
    distributorLogoURL: { displayFormat: '![#NAME](#VALUE)' },
    distributionDate: { displayFormat: '' },
    depositor: { displayFormat: '' },
    dateOfDeposit: { displayFormat: '' },
    timePeriodCovered: { displayFormat: ';' },
    timePeriodCoveredStart: { displayFormat: '#NAME: #VALUE ' },
    timePeriodCoveredEnd: { displayFormat: '#NAME: #VALUE ' },
    dateOfCollection: { displayFormat: ';' },
    dateOfCollectionStart: { displayFormat: '#NAME: #VALUE ' },
    dateOfCollectionEnd: { displayFormat: '#NAME: #VALUE ' },
    kindOfData: { displayFormat: '' },
    series: { displayFormat: ':' },
    seriesName: { displayFormat: '#VALUE' },
    seriesInformation: { displayFormat: '#VALUE' },
    software: { displayFormat: ',' },
    softwareName: { displayFormat: '#VALUE' },
    softwareVersion: { displayFormat: '#NAME: #VALUE' },
    relatedMaterial: { displayFormat: '' },
    relatedDatasets: { displayFormat: '' },
    otherReferences: { displayFormat: '' },
    dataSources: { displayFormat: '' },
    originOfSources: { displayFormat: '' },
    characteristicOfSources: { displayFormat: '' },
    accessToSources: { displayFormat: '' }
  }
}
